/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AcademicLeader;



/**
 *
 * @author Justin Yong
 */
public class academicLeader extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(academicLeader.class.getName());
    private static final String ACADEMIC_LEADER_FILE = "src/main/java/oopwj/Data/academicLeader.txt";
    private String loggedInUserID;  // Store logged-in user ID

    /**
     * Creates new form MainPage
     */
    public academicLeader() {
        initComponents();
        updateAcNameLabel();
    }
    
    /**
     * Constructor with user session
     * @param userID - The logged-in user's ID
     */
    public academicLeader(String userID) {
        this.loggedInUserID = userID;
        initComponents();
        updateAcNameLabel();
        logger.info("Academic Leader logged in: " + userID);
    }
    
    /**
     * Get the currently logged-in user ID
     * @return userID or null if not logged in
     */
    public String getLoggedInUserID() {
        return loggedInUserID;
    }
    
    /**
     * Clear user session (for logout)
     */
    public void clearSession() {
        this.loggedInUserID = null;
        logger.info("Academic Leader session cleared");
    }

    private void updateAcNameLabel() {
        String name = getAcademicLeaderNameById(loggedInUserID);
        if (name == null || name.isEmpty()) {
            acName.setText("Academic Leader");
        } else {
            acName.setText(name);
        }
    }

    private String getAcademicLeaderNameById(String userID) {
        if (userID == null || userID.isEmpty()) {
            return null;
        }

        try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader(ACADEMIC_LEADER_FILE))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }
                String[] parts = line.split(",");
                if (parts.length < 2) {
                    continue;
                }
                if (parts[0].trim().equalsIgnoreCase(userID.trim())) {
                    return parts[1].trim();
                }
            }
        } catch (java.io.IOException e) {
            logger.warning("Failed to read academic leader data: " + e.getMessage());
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modules = new javax.swing.JToggleButton();
        generateReports = new javax.swing.JToggleButton();
        welcome = new javax.swing.JLabel();
        logOut = new javax.swing.JToggleButton();
        profile = new javax.swing.JToggleButton();
        lecturerReview = new javax.swing.JToggleButton();
        acName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modules.setText("Modules");
        modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulesActionPerformed(evt);
            }
        });

        generateReports.setText("Reports");
        generateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsActionPerformed(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcome.setText("Welcome, Academic Leader");

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        lecturerReview.setText("Lecturer Review");
        lecturerReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerReviewActionPerformed(evt);
            }
        });

        acName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lecturerReview)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(acName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acName)
                .addGap(31, 31, 31)
                .addComponent(profile)
                .addGap(28, 28, 28)
                .addComponent(modules)
                .addGap(27, 27, 27)
                .addComponent(generateReports)
                .addGap(27, 27, 27)
                .addComponent(lecturerReview)
                .addGap(26, 26, 26)
                .addComponent(logOut)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulesActionPerformed
        // TODO add your handling code here:
        modules m = new modules(this.loggedInUserID, this);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modulesActionPerformed

    private void generateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsActionPerformed
        // TODO add your handling code here:
        generateReports gr = new generateReports(this.loggedInUserID, this);
        gr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_generateReportsActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            clearSession();  // Clear user session
            this.dispose();
            new oopwj.LoginFrame();  // Return to login page
        }
    }//GEN-LAST:event_logOutActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        editProfileAC ed = new editProfileAC(this.loggedInUserID, this);
        ed.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_profileActionPerformed

    private void lecturerReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerReviewActionPerformed
        // TODO add your handling code here:
        lecturerReview lr = new lecturerReview(this.loggedInUserID, this);
        lr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lecturerReviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form - Must login first */
        java.awt.EventQueue.invokeLater(() -> new oopwj.LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acName;
    private javax.swing.JToggleButton generateReports;
    private javax.swing.JToggleButton lecturerReview;
    private javax.swing.JToggleButton logOut;
    private javax.swing.JToggleButton modules;
    private javax.swing.JToggleButton profile;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
