/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AcademicLeader;



/**
 *
 * @author Justin Yong
 */
public class academicLeader extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(academicLeader.class.getName());
    private String loggedInUserID;  // Store logged-in user ID

    /**
     * Creates new form MainPage
     */
    public academicLeader() {
        initComponents();
    }
    
    /**
     * Constructor with user session
     * @param userID - The logged-in user's ID
     */
    public academicLeader(String userID) {
        this.loggedInUserID = userID;
        initComponents();
        logger.info("Academic Leader logged in: " + userID);
    }
    
    /**
     * Get the currently logged-in user ID
     * @return userID or null if not logged in
     */
    public String getLoggedInUserID() {
        return loggedInUserID;
    }
    
    /**
     * Clear user session (for logout)
     */
    public void clearSession() {
        this.loggedInUserID = null;
        logger.info("Academic Leader session cleared");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modules = new javax.swing.JToggleButton();
        generateReports = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        logOut = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modules.setText("Modules");
        modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulesActionPerformed(evt);
            }
        });

        generateReports.setText("Reports");
        generateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Welcome, Academic Leader");

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modules)
                            .addComponent(generateReports)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOut)
                        .addGap(123, 123, 123)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(modules)
                .addGap(30, 30, 30)
                .addComponent(generateReports)
                .addGap(31, 31, 31)
                .addComponent(logOut)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulesActionPerformed
        // TODO add your handling code here:
        modules m = new modules(this.loggedInUserID, this);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modulesActionPerformed

    private void generateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsActionPerformed
        // TODO add your handling code here:
        generateReports gr = new generateReports(this.loggedInUserID, this);
        gr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_generateReportsActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            clearSession();  // Clear user session
            this.dispose();
            new oopwj.LoginFrame();  // Return to login page
        }
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form - Must login first */
        java.awt.EventQueue.invokeLater(() -> new oopwj.LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton generateReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton logOut;
    private javax.swing.JToggleButton modules;
    // End of variables declaration//GEN-END:variables
}
