/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AcademicLeader;

import java.io.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Justin Yong
 */
public class generateReports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(generateReports.class.getName());
    private String academicLeaderID;  // Store the logged-in Academic Leader ID
    private academicLeader parentWindow;  // Store reference to parent window
    private static final String MODULE_PLACEHOLDER = "Module";
    private static final String QUIZ_PLACEHOLDER = "Quiz";
    private final Map<String, String> moduleNameToId = new HashMap<>();
    private final Map<String, String> quizNameToId = new HashMap<>();

    /**
     * Creates new form generateReports
     */
    public generateReports() {
        this(null, null);  // Default constructor for backward compatibility
    }
    
    /**
     * Constructor with Academic Leader ID for filtering
     */
    public generateReports(String academicLeaderID) {
        this(academicLeaderID, null);  // Constructor with user ID only
    }
    
    /**
     * Constructor with Academic Leader ID and parent window reference
     */
    public generateReports(String academicLeaderID, academicLeader parentWindow) {
        this.academicLeaderID = academicLeaderID;
        this.parentWindow = parentWindow;
        initComponents();
        loadModulesFromFile();
        resetQuizDropdown();
        setDefaultPlaceholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modules = new javax.swing.JComboBox<>();
        exit = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        quiz = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulesActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 51, 51));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Report");

        quiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(modules, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(exit)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if (parentWindow != null) {
            parentWindow.setVisible(true);  // Return to parent window with session preserved
        } else {
            academicLeader al = new academicLeader(academicLeaderID);  // Create with session ID
            al.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void modulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulesActionPerformed
        String selectedModuleName = (String) modules.getSelectedItem();
        if (selectedModuleName == null || selectedModuleName.equals(MODULE_PLACEHOLDER)) {
            resetQuizDropdown();
            return;
        }

        String moduleId = moduleNameToId.get(selectedModuleName);
        if (moduleId != null) {
            loadQuizzesForModule(moduleId);
            modules.setForeground(Color.BLACK);
        } else {
            resetQuizDropdown();
        }
    }//GEN-LAST:event_modulesActionPerformed

    private void quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizActionPerformed
        String selectedQuizName = (String) quiz.getSelectedItem();
        if (selectedQuizName != null && !selectedQuizName.equals(QUIZ_PLACEHOLDER)) {
            quiz.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_quizActionPerformed

    private void loadModulesFromFile() {
        modules.removeAllItems();
        moduleNameToId.clear();
        modules.addItem(MODULE_PLACEHOLDER);
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\modules.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 3) {
                        String moduleId = parts[0].trim();
                        String moduleName = parts[1].trim();
                        String moduleACID = parts[2].trim();  // Academic Leader ID
                        
                        // Filter modules: only show modules under this Academic Leader
                        if (this.academicLeaderID != null && !moduleACID.equals(this.academicLeaderID)) {
                            continue;  // Skip modules not belonging to this AC
                        }

                        modules.addItem(moduleName);
                        moduleNameToId.put(moduleName, moduleId);
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load modules list", e);
            modules.addItem("Error loading modules");
        }
    }

    private void loadQuizzesForModule(String moduleId) {
        quiz.removeAllItems();
        quizNameToId.clear();
        quiz.addItem(QUIZ_PLACEHOLDER);
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Quiz.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 3) {
                        String quizId = parts[0].trim();
                        String quizModuleId = parts[1].trim();
                        String quizName = parts[2].trim();
                        if (quizModuleId.equals(moduleId)) {
                            quiz.addItem(quizName);
                            quizNameToId.put(quizName, quizId);
                        }
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load quiz list", e);
            quiz.addItem("Error loading quiz");
        }
        quiz.setForeground(Color.GRAY);
    }

    private void setDefaultPlaceholders() {
        modules.setForeground(Color.GRAY);
        quiz.setForeground(Color.GRAY);
    }

    private void resetQuizDropdown() {
        quiz.removeAllItems();
        quiz.addItem(QUIZ_PLACEHOLDER);
        quiz.setForeground(Color.GRAY);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form - Must login first */
        java.awt.EventQueue.invokeLater(() -> new oopwj.LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> modules;
    private javax.swing.JComboBox<String> quiz;
    // End of variables declaration//GEN-END:variables
}
