/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AcademicLeader;

import java.io.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Justin Yong
 */
public class generateReports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(generateReports.class.getName());
    private String academicLeaderID;  // Store the logged-in Academic Leader ID
    private academicLeader parentWindow;  // Store reference to parent window
    private static final String MODULE_PLACEHOLDER = "Module";
    private static final String QUIZ_PLACEHOLDER = "Quiz";
    private final Map<String, String> moduleNameToId = new HashMap<>();
    private final Map<String, String> quizNameToId = new HashMap<>();
    private final Map<String, String> studentIdToName = new HashMap<>();

    /**
     * Creates new form generateReports
     */
    public generateReports() {
        this(null, null);  // Default constructor for backward compatibility
    }
    
    /**
     * Constructor with Academic Leader ID for filtering
     */
    public generateReports(String academicLeaderID) {
        this(academicLeaderID, null);  // Constructor with user ID only
    }
    
    /**
     * Constructor with Academic Leader ID and parent window reference
     */
    public generateReports(String academicLeaderID, academicLeader parentWindow) {
        this.academicLeaderID = academicLeaderID;
        this.parentWindow = parentWindow;
        initComponents();
        loadStudentNamesFromFile();
        loadModulesFromFile();
        resetQuizDropdown();
        setDefaultPlaceholders();
        resetReportLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modules = new javax.swing.JComboBox<>();
        exit = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        quiz = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passRate = new javax.swing.JLabel();
        numberOfStudents = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        highestMark = new javax.swing.JLabel();
        studentNameHighest = new javax.swing.JLabel();
        studentIDHighest = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lowestMark = new javax.swing.JLabel();
        studentNameLowest = new javax.swing.JLabel();
        studentIDLowest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulesActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 51, 51));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Report");

        quiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Total Pass Rate");

        passRate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passRate.setText("jLabel3");

        numberOfStudents.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(passRate))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(passRate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numberOfStudents)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Highest Mark");

        highestMark.setText("jLabel4");

        studentNameHighest.setText("jLabel5");

        studentIDHighest.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Lowest Mark");

        lowestMark.setText("jLabel5");

        studentNameLowest.setText("jLabel5");

        studentIDLowest.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(studentNameLowest, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIDLowest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(highestMark, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(studentNameHighest, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIDHighest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(lowestMark, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highestMark)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameHighest)
                    .addComponent(studentIDHighest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowestMark)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLowest)
                    .addComponent(studentIDLowest))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modules, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quiz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(exit)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(389, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if (parentWindow != null) {
            parentWindow.setVisible(true);  // Return to parent window with session preserved
        } else {
            academicLeader al = new academicLeader(academicLeaderID);  // Create with session ID
            al.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void modulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulesActionPerformed
        String selectedModuleName = (String) modules.getSelectedItem();
        if (selectedModuleName == null || selectedModuleName.equals(MODULE_PLACEHOLDER)) {
            resetQuizDropdown();
            return;
        }

        String moduleId = moduleNameToId.get(selectedModuleName);
        if (moduleId != null) {
            loadQuizzesForModule(moduleId);
            modules.setForeground(Color.BLACK);
        } else {
            resetQuizDropdown();
        }
    }//GEN-LAST:event_modulesActionPerformed

    private void quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizActionPerformed
        String selectedQuizName = (String) quiz.getSelectedItem();
        if (selectedQuizName != null && !selectedQuizName.equals(QUIZ_PLACEHOLDER)) {
            quiz.setForeground(Color.BLACK);
            String quizId = quizNameToId.get(selectedQuizName);
            if (quizId != null) {
                updateReportForQuiz(quizId);
            } else {
                resetReportLabels();
            }
        } else {
            resetReportLabels();
        }
    }//GEN-LAST:event_quizActionPerformed

    private void loadModulesFromFile() {
        modules.removeAllItems();
        moduleNameToId.clear();
        modules.addItem(MODULE_PLACEHOLDER);
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\modules.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 3) {
                        String moduleId = parts[0].trim();
                        String moduleName = parts[1].trim();
                        String moduleACID = parts[2].trim();  // Academic Leader ID
                        
                        // Filter modules: only show modules under this Academic Leader
                        if (this.academicLeaderID != null && !moduleACID.equals(this.academicLeaderID)) {
                            continue;  // Skip modules not belonging to this AC
                        }

                        modules.addItem(moduleName);
                        moduleNameToId.put(moduleName, moduleId);
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load modules list", e);
            modules.addItem("Error loading modules");
        }
    }

    private void loadQuizzesForModule(String moduleId) {
        quiz.removeAllItems();
        quizNameToId.clear();
        quiz.addItem(QUIZ_PLACEHOLDER);
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Quiz.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 3) {
                        String quizId = parts[0].trim();
                        String quizModuleId = parts[1].trim();
                        String quizName = parts[2].trim();
                        if (quizModuleId.equals(moduleId)) {
                            quiz.addItem(quizName);
                            quizNameToId.put(quizName, quizId);
                        }
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load quiz list", e);
            quiz.addItem("Error loading quiz");
        }
        quiz.setForeground(Color.GRAY);
    }

    private void loadStudentNamesFromFile() {
        studentIdToName.clear();
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\student.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 2) {
                        String studentId = parts[0].trim();
                        String studentName = parts[1].trim();
                        studentIdToName.put(studentId, studentName);
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load student list", e);
        }
    }

    private void updateReportForQuiz(String quizId) {
        int totalStudents = 0;
        int passedStudents = 0;
        Integer highest = null;
        Integer lowest = null;
        String highestStudentId = "";
        String lowestStudentId = "";

        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\FinalGrade.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (trimmed.isEmpty()) {
                    continue;
                }
                String[] parts = trimmed.split(",");
                if (parts.length >= 5) {
                    String studentId = parts[0].trim();
                    String quizIdInFile = parts[2].trim();
                    String markStr = parts[3].trim();
                    String grade = parts[4].trim();

                    if (!quizIdInFile.equals(quizId)) {
                        continue;
                    }

                    int mark;
                    try {
                        mark = Integer.parseInt(markStr);
                    } catch (NumberFormatException ex) {
                        continue;
                    }

                    totalStudents++;
                    if (!"F".equalsIgnoreCase(grade)) {
                        passedStudents++;
                    }

                    if (highest == null || mark > highest) {
                        highest = mark;
                        highestStudentId = studentId;
                    }
                    if (lowest == null || mark < lowest) {
                        lowest = mark;
                        lowestStudentId = studentId;
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load final grades", e);
        }

        if (totalStudents == 0) {
            resetReportLabels();
            return;
        }

        double passRateValue = (passedStudents * 100.0) / totalStudents;
        passRate.setText(String.format("%.2f%%", passRateValue));
        
        // Set color based on pass rate
        if (passRateValue >= 70) {
            passRate.setForeground(new Color(0, 128, 0));  // Green
        } else if (passRateValue >= 50) {
            passRate.setForeground(new Color(255, 193, 7));  // Yellow
        } else {
            passRate.setForeground(new Color(255, 0, 0));  // Red
        }
        
        // Set student count label
        numberOfStudents.setText(passedStudents + " out of " + totalStudents + " students");

        if (highest != null) {
            highestMark.setText(String.valueOf(highest));
            studentIDHighest.setText(highestStudentId);
            studentNameHighest.setText(studentIdToName.getOrDefault(highestStudentId, "Unknown"));
        }

        if (lowest != null) {
            lowestMark.setText(String.valueOf(lowest));
            studentIDLowest.setText(lowestStudentId);
            studentNameLowest.setText(studentIdToName.getOrDefault(lowestStudentId, "Unknown"));
        }
    }

    private void setDefaultPlaceholders() {
        modules.setForeground(Color.GRAY);
        quiz.setForeground(Color.GRAY);
    }

    private void resetQuizDropdown() {
        quiz.removeAllItems();
        quiz.addItem(QUIZ_PLACEHOLDER);
        quiz.setForeground(Color.GRAY);
    }

    private void resetReportLabels() {
        passRate.setText("-");
        passRate.setForeground(Color.BLACK);
        numberOfStudents.setText("-");
        highestMark.setText("-");
        studentNameHighest.setText("-");
        studentIDHighest.setText("-");
        lowestMark.setText("-");
        studentNameLowest.setText("-");
        studentIDLowest.setText("-");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form - Must login first */
        java.awt.EventQueue.invokeLater(() -> new oopwj.LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton exit;
    private javax.swing.JLabel highestMark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lowestMark;
    private javax.swing.JComboBox<String> modules;
    private javax.swing.JLabel numberOfStudents;
    private javax.swing.JLabel passRate;
    private javax.swing.JComboBox<String> quiz;
    private javax.swing.JLabel studentIDHighest;
    private javax.swing.JLabel studentIDLowest;
    private javax.swing.JLabel studentNameHighest;
    private javax.swing.JLabel studentNameLowest;
    // End of variables declaration//GEN-END:variables
}
