/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AcademicLeader;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.awt.GridLayout;
import javax.swing.table.*;
import java.awt.*;
import javax.swing.JButton;

/**
 *
 * @author Justin Yong
 */
public class modules extends javax.swing.JFrame {
    
    private DefaultTableModel model = new DefaultTableModel();
    private String columnNames[] = {"Module ID", "Module Name", "Lecturer"};
    private final List<String> lecturers = new ArrayList<>();
    private final Map<String, String> lecturerIdToName = new HashMap<>();
    private final Map<String, String> lecturerNameToId = new HashMap<>();
    private String academicLeaderID;
    private academicLeader parentWindow;
    
    public modules() {
        this(null, null);
    }
    
    public modules(String academicLeaderID) {
        this(academicLeaderID, null);
    }
    
    public modules(String academicLeaderID, academicLeader parentWindow) {
        this.academicLeaderID = academicLeaderID;
        this.parentWindow = parentWindow;
        try{
        model.setColumnIdentifiers(columnNames);
        loadLecturersFromFile();
        FileReader fr = new FileReader("src\\main\\java\\oopwj\\Data\\modules.txt");
        BufferedReader br = new BufferedReader(fr);
        
        String line = null;
        
        while ((line = br.readLine()) != null){
            String values[] = line.split(",");
            for (int i = 0; i < values.length; i++) {
                values[i] = values[i].trim();
            }
            
            if (values.length >= 3) {
                String moduleACID = values[2];
                
                if (this.academicLeaderID != null && !moduleACID.equals(this.academicLeaderID)) {
                    continue;
                }
                
                String lecturerName = lecturerIdToName.getOrDefault(values[3], values[3]);
                model.addRow(new Object[]{values[0], values[1], lecturerName});
            } else if (values.length == 2) {
                if (this.academicLeaderID == null) {
                    model.addRow(new Object[]{values[0], values[1], "NONE"});
                }
            }
        }
        br.close();
        fr.close();
        
        } catch(Exception e){
            
        }
       
        
        initComponents();
        setLocationRelativeTo(null);
        enableSearch();
        addHoverEffect(addModule, new Color(70,130,180), new Color(100,149,237));
        addHoverEffect(editModule, new Color(70,130,180), new Color(100,149,237));
        addHoverEffect(deleteModule, new Color(70,130,180), new Color(100,149,237));
        addHoverEffect(exit, new Color(220,80,80), new Color(255,120,120));
    }
    
    private void addHoverEffect(JButton btn, Color normal, Color hover) {
        btn.setOpaque(true);
        btn.setContentAreaFilled(true);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);

        btn.setBackground(normal);
        btn.setForeground(Color.WHITE);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(normal);
            }
        });
    }

    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modules.class.getName());

    /**
     * Creates new form Modules
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;

                GradientPaint gp = new GradientPaint(
                    0, 0, new Color(230, 240, 255),
                    0, getHeight(), new Color(245, 247, 250)
                );

                g2.setPaint(gp);
                g2.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        modulesList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addModule = new javax.swing.JButton();
        editModule = new javax.swing.JButton();
        deleteModule = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);

        modulesList.setModel(model);
        jScrollPane1.setViewportView(modulesList);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Modules List");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Search:");

        addModule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addModule.setText("Add");
        addModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModuleActionPerformed(evt);
            }
        });

        editModule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editModule.setText("Edit");
        editModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editModuleActionPerformed(evt);
            }
        });

        deleteModule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteModule.setText("Delete");
        deleteModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteModuleActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(220, 80, 80));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(addModule)
                                .addGap(18, 18, 18)
                                .addComponent(editModule)
                                .addGap(18, 18, 18)
                                .addComponent(deleteModule)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addModule)
                    .addComponent(editModule)
                    .addComponent(deleteModule))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModuleActionPerformed
        // TODO add your handling code here:
        String nextId = getNextModuleId();

        JTextField moduleNameField = new JTextField();
        JComboBox<String> lecturerCombo;

        if (lecturers.isEmpty()) {
            lecturerCombo = new JComboBox<>(new String[]{"NONE"});
        } else {
            java.util.List<String> options = new ArrayList<>(lecturers);
            options.add(0, "NONE");
            lecturerCombo = new JComboBox<>(options.toArray(new String[0]));
        }

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Module name:"));
        panel.add(moduleNameField);
        panel.add(new JLabel("Lecturer:"));
        panel.add(lecturerCombo);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add Module", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String newModuleName = moduleNameField.getText().trim();
        String selectedLecturerName = (String) lecturerCombo.getSelectedItem();
        if (selectedLecturerName == null) {
            selectedLecturerName = "NONE";
        }

        if (newModuleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Module name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.addRow(new Object[]{nextId, newModuleName, selectedLecturerName});

        saveData();
        JOptionPane.showMessageDialog(this, "New module added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addModuleActionPerformed

    private void editModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editModuleActionPerformed
        // TODO add your handling code here:
        int selectedRow = modulesList.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module to edit.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String moduleId = model.getValueAt(selectedRow, 0).toString();
        String currentModuleName = model.getValueAt(selectedRow, 1).toString();
        String currentLecturerName = model.getValueAt(selectedRow, 2).toString();

        JTextField moduleNameField = new JTextField(currentModuleName);
        JComboBox<String> lecturerCombo;

        if (lecturers.isEmpty()) {
            lecturerCombo = new JComboBox<>(new String[]{"NONE"});
        } else {
            java.util.List<String> options = new ArrayList<>(lecturers);
            options.add(0, "NONE");
            lecturerCombo = new JComboBox<>(options.toArray(new String[0]));
        }
        lecturerCombo.setSelectedItem(currentLecturerName);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Module name:"));
        panel.add(moduleNameField);
        panel.add(new JLabel("Lecturer:"));
        panel.add(lecturerCombo);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Module", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String newModuleName = moduleNameField.getText().trim();
        String selectedLecturerName = (String) lecturerCombo.getSelectedItem();
        if (selectedLecturerName == null) {
            selectedLecturerName = "NONE";
        }

        if (newModuleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Module name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.setValueAt(newModuleName, selectedRow, 1);
        model.setValueAt(selectedLecturerName, selectedRow, 2);

        saveData();
        JOptionPane.showMessageDialog(this, "Module updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_editModuleActionPerformed

    private void deleteModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteModuleActionPerformed
        // TODO add your handling code here:
        int selectedRow = modulesList.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this module?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            model.removeRow(selectedRow);
            saveData();
            JOptionPane.showMessageDialog(this, "Module deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteModuleActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if (parentWindow != null) {
            parentWindow.setVisible(true);
        } else {
            academicLeader al = new academicLeader(academicLeaderID);
            al.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void saveData () {
        try {
            List<String> allLines = new ArrayList<>();
            Map<String, int[]> currentModuleMap = new HashMap<>();
            
            try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Data\\modules.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String trimmed = line.trim();
                    if (!trimmed.isEmpty()) {
                        allLines.add(trimmed);
                    }
                }
            } catch (IOException e) {
            }
            
            for (int i = 0; i < model.getRowCount(); i++) {
                String moduleId = model.getValueAt(i, 0).toString();
                currentModuleMap.put(moduleId, new int[]{i, 1});
            }
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("src\\main\\java\\oopwj\\Data\\modules.txt"))) {
                for (String line : allLines) {
                    String[] parts = line.split(",");
                    if (parts.length >= 3) {
                        String moduleId = parts[0].trim();
                        String academicLeaderId = parts[2].trim();
                        
                        if (academicLeaderId.equals(this.academicLeaderID)) {
                            int[] modelInfo = currentModuleMap.get(moduleId);
                            if (modelInfo != null && modelInfo[1] == 1) {
                                int modelRow = modelInfo[0];
                                String moduleName = model.getValueAt(modelRow, 1).toString();
                                String lecturerName = model.getValueAt(modelRow, 2).toString();
                                String lecturerId = lecturerNameToId.getOrDefault(lecturerName, lecturerName);
                                writer.write(moduleId + "," + moduleName + "," + this.academicLeaderID + "," + lecturerId);
                                writer.newLine();
                                modelInfo[1] = 0;
                            }
                        } else {
                            writer.write(line);
                            writer.newLine();
                        }
                    }
                }
                
                for (int i = 0; i < model.getRowCount(); i++) {
                    String moduleId = model.getValueAt(i, 0).toString();
                    int[] modelInfo = currentModuleMap.get(moduleId);
                    if (modelInfo != null && modelInfo[1] == 1) {
                        String moduleName = model.getValueAt(i, 1).toString();
                        String lecturerName = model.getValueAt(i, 2).toString();
                        String lecturerId = lecturerNameToId.getOrDefault(lecturerName, lecturerName);
                        writer.write(moduleId + "," + moduleName + "," + this.academicLeaderID + "," + lecturerId);
                        writer.newLine();
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving the data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadLecturersFromFile() {
        lecturers.clear();
        lecturerIdToName.clear();
        lecturerNameToId.clear();
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Data\\lecturer.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 5) {
                        String id = parts[0].trim();
                        String name = parts[1].trim();
                        String lecturerACID = parts[4].trim();
                        
                        if (this.academicLeaderID != null && !lecturerACID.equals(this.academicLeaderID)) {
                            continue;
                        }
                        
                        lecturers.add(name);
                        lecturerIdToName.put(id, name);
                        lecturerNameToId.put(name, id);
                    } else if (parts.length >= 2) {
                        String id = parts[0].trim();
                        String name = parts[1].trim();
                        if (this.academicLeaderID == null) {
                            lecturers.add(name);
                            lecturerIdToName.put(id, name);
                            lecturerNameToId.put(name, id);
                        }
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load lecturers list", e);
        }
    }

    private String getNextModuleId() {
        int maxId = 0;
        
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Data\\modules.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length > 0) {
                        String id = parts[0].trim();
                        if (id.matches("M\\d+")) {
                            try {
                                int numeric = Integer.parseInt(id.substring(1));
                                if (numeric > maxId) {
                                    maxId = numeric;
                                }
                            } catch (NumberFormatException ignored) {
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to read modules file for ID generation", e);
        }
        
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 0);
            if (value != null) {
                String id = value.toString().trim();
                if (id.matches("M\\d+")) {
                    try {
                        int numeric = Integer.parseInt(id.substring(1));
                        if (numeric > maxId) {
                            maxId = numeric;
                        }
                    } catch (NumberFormatException ignored) {
                    }
                }
            }
        }
        
        return String.format("M%03d", maxId + 1);
    }
    
    private void enableSearch() {
        TableRowSorter<DefaultTableModel> moduleSorter =
            new TableRowSorter<>((DefaultTableModel) modulesList.getModel());
        modulesList.setRowSorter(moduleSorter);

        searchBar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(); }

            private void filter() {
                String text = searchBar.getText();
                moduleSorter.setRowFilter(text.isEmpty() ? null :
                RowFilter.regexFilter("(?i)" + text));
            }
        });
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new oopwj.LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModule;
    private javax.swing.JButton deleteModule;
    private javax.swing.JButton editModule;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable modulesList;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
