/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AcademicLeader;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.awt.GridLayout;
import javax.swing.table.*;

/**
 *
 * @author Justin Yong
 */
public class modules extends javax.swing.JFrame {
    
    private DefaultTableModel model = new DefaultTableModel();
    private String columnNames[] = {"Module ID", "Module Name", "Lecturer"};
    private final List<String> lecturers = new ArrayList<>();
    private final Map<String, String> lecturerIdToName = new HashMap<>();
    private final Map<String, String> lecturerNameToId = new HashMap<>();
    private String academicLeaderID;  // Store the logged-in Academic Leader ID
    private academicLeader parentWindow;  // Store reference to parent window
    
    public modules() {
        this(null, null);  // Default constructor for backward compatibility
    }
    
    public modules(String academicLeaderID) {
        this(academicLeaderID, null);  // Constructor with user ID only
    }
    
    public modules(String academicLeaderID, academicLeader parentWindow) {
        this.academicLeaderID = academicLeaderID;
        this.parentWindow = parentWindow;
        try{
        model.setColumnIdentifiers(columnNames);
        loadLecturersFromFile();
        FileReader fr = new FileReader("src\\main\\java\\oopwj\\Data\\modules.txt");
        BufferedReader br = new BufferedReader(fr);
        
        String line = null;
        
        while ((line = br.readLine()) != null){
            String values[] = line.split(",");
            for (int i = 0; i < values.length; i++) {
                values[i] = values[i].trim();
            }
            
            // Filter modules: only show modules under this Academic Leader
            if (values.length >= 3) {
                String moduleACID = values[2];  // Academic Leader ID
                
                // If academicLeaderID is set, only show modules belonging to this AC
                if (this.academicLeaderID != null && !moduleACID.equals(this.academicLeaderID)) {
                    continue;  // Skip modules not belonging to this AC
                }
                
                String lecturerName = lecturerIdToName.getOrDefault(values[3], values[3]);
                model.addRow(new Object[]{values[0], values[1], lecturerName});
            } else if (values.length == 2) {
                // For backward compatibility, check if we should still display
                if (this.academicLeaderID == null) {
                    model.addRow(new Object[]{values[0], values[1], "NONE"});
                }
            }
        }
        br.close();
        fr.close();
        
        } catch(Exception e){
            
        }
       
        
        initComponents();
        enableSearch();
    }

    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modules.class.getName());

    /**
     * Creates new form Modules
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modulesList = new javax.swing.JTable();
        Add = new javax.swing.JToggleButton();
        Edit = new javax.swing.JToggleButton();
        Delete = new javax.swing.JToggleButton();
        Exit = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modulesList.setModel(model);
        jScrollPane1.setViewportView(modulesList);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 51, 102));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modules List");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Add)
                        .addGap(41, 41, 41)
                        .addComponent(Edit)
                        .addGap(40, 40, 40)
                        .addComponent(Delete)
                        .addGap(173, 173, 173))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(198, 198, 198)
                        .addComponent(Exit)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Edit)
                    .addComponent(Delete))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        String nextId = getNextModuleId();

        JTextField moduleNameField = new JTextField();
        JComboBox<String> lecturerCombo;

        if (lecturers.isEmpty()) {
            lecturerCombo = new JComboBox<>(new String[]{"NONE"});
        } else {
            java.util.List<String> options = new ArrayList<>(lecturers);
            options.add(0, "NONE");
            lecturerCombo = new JComboBox<>(options.toArray(new String[0]));
        }

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Module name:"));
        panel.add(moduleNameField);
        panel.add(new JLabel("Lecturer:"));
        panel.add(lecturerCombo);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add Module", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String newModuleName = moduleNameField.getText().trim();
        String selectedLecturerName = (String) lecturerCombo.getSelectedItem();
        if (selectedLecturerName == null) {
            selectedLecturerName = "NONE";
        }

        if (newModuleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Module name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.addRow(new Object[]{nextId, newModuleName, selectedLecturerName});

        saveData();
        JOptionPane.showMessageDialog(this, "New module added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AddActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        int selectedRow = modulesList.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module to edit.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String moduleId = model.getValueAt(selectedRow, 0).toString();
        String currentModuleName = model.getValueAt(selectedRow, 1).toString();
        String currentLecturerName = model.getValueAt(selectedRow, 2).toString();

        JTextField moduleNameField = new JTextField(currentModuleName);
        JComboBox<String> lecturerCombo;

        if (lecturers.isEmpty()) {
            lecturerCombo = new JComboBox<>(new String[]{"NONE"});
        } else {
            java.util.List<String> options = new ArrayList<>(lecturers);
            options.add(0, "NONE");
            lecturerCombo = new JComboBox<>(options.toArray(new String[0]));
        }
        lecturerCombo.setSelectedItem(currentLecturerName);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Module name:"));
        panel.add(moduleNameField);
        panel.add(new JLabel("Lecturer:"));
        panel.add(lecturerCombo);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Module", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String newModuleName = moduleNameField.getText().trim();
        String selectedLecturerName = (String) lecturerCombo.getSelectedItem();
        if (selectedLecturerName == null) {
            selectedLecturerName = "NONE";
        }

        if (newModuleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Module name cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.setValueAt(newModuleName, selectedRow, 1);
        model.setValueAt(selectedLecturerName, selectedRow, 2);

        saveData();
        JOptionPane.showMessageDialog(this, "Module updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = modulesList.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this module?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            model.removeRow(selectedRow);
            saveData();
            JOptionPane.showMessageDialog(this, "Module deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        if (parentWindow != null) {
            parentWindow.setVisible(true);  // Return to parent window with session preserved
        } else {
            academicLeader al = new academicLeader(academicLeaderID);  // Create with session ID
            al.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void saveData () {
        try {
            // First, read all existing modules from file and maintain order
            List<String> allLines = new ArrayList<>();
            Map<String, int[]> currentModuleMap = new HashMap<>();  // moduleId -> [modelRowIndex, exists]
            
            try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Data\\modules.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String trimmed = line.trim();
                    if (!trimmed.isEmpty()) {
                        allLines.add(trimmed);
                    }
                }
            } catch (IOException e) {
                // File might not exist yet, that's okay
            }
            
            // Build a map of current modules for quick lookup
            for (int i = 0; i < model.getRowCount(); i++) {
                String moduleId = model.getValueAt(i, 0).toString();
                currentModuleMap.put(moduleId, new int[]{i, 1});  // row index and exists flag
            }
            
            // Now write back in original order, updating current academic leader's modules
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("src\\main\\java\\oopwj\\Data\\modules.txt"))) {
                // Process existing lines in order
                for (String line : allLines) {
                    String[] parts = line.split(",");
                    if (parts.length >= 3) {
                        String moduleId = parts[0].trim();
                        String academicLeaderId = parts[2].trim();
                        
                        // If this module belongs to the current academic leader, update it from model
                        if (academicLeaderId.equals(this.academicLeaderID)) {
                            int[] modelInfo = currentModuleMap.get(moduleId);
                            if (modelInfo != null && modelInfo[1] == 1) {
                                // Found in model, write updated version
                                int modelRow = modelInfo[0];
                                String moduleName = model.getValueAt(modelRow, 1).toString();
                                String lecturerName = model.getValueAt(modelRow, 2).toString();
                                String lecturerId = lecturerNameToId.getOrDefault(lecturerName, lecturerName);
                                writer.write(moduleId + "," + moduleName + "," + this.academicLeaderID + "," + lecturerId);
                                writer.newLine();
                                modelInfo[1] = 0;  // Mark as written
                            }
                            // If not found in model, it was deleted, so skip it
                        } else {
                            // This module belongs to another academic leader, keep as is
                            writer.write(line);
                            writer.newLine();
                        }
                    }
                }
                
                // Write any new modules that weren't in the original file
                for (int i = 0; i < model.getRowCount(); i++) {
                    String moduleId = model.getValueAt(i, 0).toString();
                    int[] modelInfo = currentModuleMap.get(moduleId);
                    if (modelInfo != null && modelInfo[1] == 1) {  // Not yet written
                        String moduleName = model.getValueAt(i, 1).toString();
                        String lecturerName = model.getValueAt(i, 2).toString();
                        String lecturerId = lecturerNameToId.getOrDefault(lecturerName, lecturerName);
                        writer.write(moduleId + "," + moduleName + "," + this.academicLeaderID + "," + lecturerId);
                        writer.newLine();
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving the data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadLecturersFromFile() {
        lecturers.clear();
        lecturerIdToName.clear();
        lecturerNameToId.clear();
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Data\\lecturer.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 5) {
                        String id = parts[0].trim();
                        String name = parts[1].trim();
                        String lecturerACID = parts[4].trim();  // Academic Leader ID
                        
                        // Filter lecturers: only add lecturers under this Academic Leader
                        if (this.academicLeaderID != null && !lecturerACID.equals(this.academicLeaderID)) {
                            continue;  // Skip lecturers not belonging to this AC
                        }
                        
                        lecturers.add(name);
                        lecturerIdToName.put(id, name);
                        lecturerNameToId.put(name, id);
                    } else if (parts.length >= 2) {
                        // For backward compatibility
                        String id = parts[0].trim();
                        String name = parts[1].trim();
                        if (this.academicLeaderID == null) {  // Only add if no filter
                            lecturers.add(name);
                            lecturerIdToName.put(id, name);
                            lecturerNameToId.put(name, id);
                        }
                    }
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load lecturers list", e);
        }
    }

    private String getNextModuleId() {
        int maxId = 0;
        
        // First, check all modules in the file (not just the current model)
        try (BufferedReader reader = new BufferedReader(new FileReader("src\\main\\java\\oopwj\\Data\\modules.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length > 0) {
                        String id = parts[0].trim();
                        if (id.matches("M\\d+")) {
                            try {
                                int numeric = Integer.parseInt(id.substring(1));
                                if (numeric > maxId) {
                                    maxId = numeric;
                                }
                            } catch (NumberFormatException ignored) {
                                // skip malformed ids
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            // File might not exist yet, that's okay
        }
        
        // Also check the current model in case new modules haven't been saved yet
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 0);
            if (value != null) {
                String id = value.toString().trim();
                if (id.matches("M\\d+")) {
                    try {
                        int numeric = Integer.parseInt(id.substring(1));
                        if (numeric > maxId) {
                            maxId = numeric;
                        }
                    } catch (NumberFormatException ignored) {
                        // skip malformed ids
                    }
                }
            }
        }
        
        return String.format("M%03d", maxId + 1);
    }
    
    private void enableSearch() {
        TableRowSorter<DefaultTableModel> moduleSorter =
            new TableRowSorter<>((DefaultTableModel) modulesList.getModel());
        modulesList.setRowSorter(moduleSorter);

        searchBar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(); }

            private void filter() {
                String text = searchBar.getText();
                moduleSorter.setRowFilter(text.isEmpty() ? null :
                RowFilter.regexFilter("(?i)" + text));
            }
        });
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form - Must login first */
        java.awt.EventQueue.invokeLater(() -> new oopwj.LoginFrame());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Add;
    private javax.swing.JToggleButton Delete;
    private javax.swing.JToggleButton Edit;
    private javax.swing.JToggleButton Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable modulesList;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
