/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.AdministrativeStaff;

import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kwany
 */
public class AssignLecturerPage extends javax.swing.JFrame {

    private final TableRowSorter<DefaultTableModel> lecturerSorter;
    private final TableRowSorter<DefaultTableModel> academicSorter;

    
    public AssignLecturerPage() {
        initComponents();
        setLocationRelativeTo(null);
        
        loadUsers(LecturerList,"src\\main\\java\\oopwj\\lecturer.txt", "Lecturer");
        loadUsers(AcademicList,"src\\main\\java\\oopwj\\academicLeader.txt", "Academic Leader");
        
        lecturerSorter = new TableRowSorter<>(
            (DefaultTableModel) LecturerList.getModel());
        LecturerList.setRowSorter(lecturerSorter);

        academicSorter = new TableRowSorter<>(
                (DefaultTableModel) AcademicList.getModel());
        AcademicList.setRowSorter(academicSorter);

        setupSearch();
        
    }
    
    public static void loadUsers(JTable table, String file, String role) {
    DefaultTableModel list = (DefaultTableModel) table.getModel();
    list.setRowCount(0);

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] values = line.split(",");
            
            if (file.equals("src\\main\\java\\oopwj\\academicLeader.txt")) {
                Object[] row = {
                    values[1].trim(),
                    values[0].trim(),
                    role
                };
                list.addRow(row);
            }

            else if (file.equals("src\\main\\java\\oopwj\\lecturer.txt")) {
                Object[] row = {
                    values[1].trim(),
                    values[0].trim(),
                    role,
                    values[4].trim()
                };
                list.addRow(row);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Failed to load users.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void setupSearch() {

    // Search for Lecturer table
    searchLecturer.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filterLecturer();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filterLecturer();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filterLecturer();
        }
    });

    // Search for Academic Leader table
    searchAcademic.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filterAcademic();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filterAcademic();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filterAcademic();
        }
    });
}
    
    private void filterLecturer() {
    String text = searchLecturer.getText();

    if (text.trim().length() == 0) {
        lecturerSorter.setRowFilter(null);
    } else {
        lecturerSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
    }
}

    private void filterAcademic() {
        String text = searchAcademic.getText();

        if (text.trim().length() == 0) {
            academicSorter.setRowFilter(null);
        } else {
            academicSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LecturerList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        AcademicList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        searchLecturer = new javax.swing.JTextField();
        searchAcademic = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assign Lecturer");

        LecturerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "User ID", "Role", "Assigned Academic Leader ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LecturerList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(LecturerList);

        AcademicList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "User ID", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(AcademicList);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Search:");

        jLabel2.setText("Search:");

        jLabel3.setText("Assign To ->");

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(69, 69, 69)
                        .addComponent(btnAssign))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchAcademic))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAcademic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssign)
                    .addComponent(btnUpdate))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new AdminMainPage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int lecturerViewRow = LecturerList.getSelectedRow();
        int academicViewRow = AcademicList.getSelectedRow();
        
        if (lecturerViewRow == -1 || academicViewRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a Lecturer and Academic Leader to assign.", 
                                          "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int lecturerRow = LecturerList.convertRowIndexToModel(lecturerViewRow);
        int academicRow = AcademicList.convertRowIndexToModel(academicViewRow);

        DefaultTableModel lecturerModel = (DefaultTableModel) LecturerList.getModel();
        DefaultTableModel academicModel = (DefaultTableModel) AcademicList.getModel();

        String lecturerName = lecturerModel.getValueAt(lecturerRow, 0).toString();
        String lecturerId   = lecturerModel.getValueAt(lecturerRow, 1).toString();
        String assignedAL   = lecturerModel.getValueAt(lecturerRow, 3) == null
                                ? "" : lecturerModel.getValueAt(lecturerRow, 3).toString();

        String academicId   = academicModel.getValueAt(academicRow, 1).toString();

        if (!assignedAL.equals("None")) {
            JOptionPane.showMessageDialog(this,
                    "This lecturer is already assigned to an Academic Leader.",
                    "Already Assigned",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Assign Lecturer:\n\n" +
                "Lecturer: " + lecturerName + " (" + lecturerId + ")\n" +
                "Academic Leader ID: " + academicId,    
                "Confirm Assignment",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        File inputFile = new File("src\\main\\java\\oopwj\\lecturer.txt");
        File tempFile  = new File("src\\main\\java\\oopwj\\lecturer_temp.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");

                if (parts[0].trim().equals(lecturerId)) {
                    writer.write(parts[0] + "," + parts[1] + "," + parts[2] + "," + parts[3] + "," + academicId);
                } else {
                    writer.write(line);
                }
                writer.newLine();
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Failed to assign lecturer.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!inputFile.delete() || !tempFile.renameTo(inputFile)) {
            JOptionPane.showMessageDialog(this,
                    "Failed to update lecturer file.",
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        loadUsers(LecturerList, "src\\main\\java\\oopwj\\lecturer.txt", "Lecturer");
        AcademicList.clearSelection();

        JOptionPane.showMessageDialog(this,
                "Lecturer assigned successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int lecturerViewRow = LecturerList.getSelectedRow();
        int academicViewRow = AcademicList.getSelectedRow();

        if (lecturerViewRow == -1 || academicViewRow == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Please select both a Lecturer and an Academic Leader to update.", 
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int lecturerRow = LecturerList.convertRowIndexToModel(lecturerViewRow);
        int academicRow = AcademicList.convertRowIndexToModel(academicViewRow);

        DefaultTableModel lecturerModel = (DefaultTableModel) LecturerList.getModel();
        DefaultTableModel academicModel = (DefaultTableModel) AcademicList.getModel();

        String lecturerName = lecturerModel.getValueAt(lecturerRow, 0).toString();
        String lecturerId   = lecturerModel.getValueAt(lecturerRow, 1).toString();
        String oldAL        = lecturerModel.getValueAt(lecturerRow, 3) == null 
                                ? "" : lecturerModel.getValueAt(lecturerRow, 3).toString();

        String newAL        = academicModel.getValueAt(academicRow, 1).toString();

        if (oldAL.equals("None")) {
            JOptionPane.showMessageDialog(this, 
                    "This lecturer is not yet assigned. Use 'Assign' button instead.", 
                    "Not Assigned", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Update Lecturer:\n\n" +
                "Lecturer: " + lecturerName + " (" + lecturerId + ")\n" +
                "Old Academic Leader ID: " + oldAL + "\n" +
                "New Academic Leader ID: " + newAL,
                "Confirm Update",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        File inputFile = new File("src\\main\\java\\oopwj\\lecturer.txt");
        File tempFile  = new File("src\\main\\java\\oopwj\\lecturer_temp.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
             BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts[0].trim().equals(lecturerId)) {
                    parts[4] = newAL; 
                }
                writer.write(String.join(",", parts));
                writer.newLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to update lecturer: " + ex.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!inputFile.delete() || !tempFile.renameTo(inputFile)) {
            JOptionPane.showMessageDialog(this, "Failed to update lecturer file.", "File Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        loadUsers(LecturerList, "src\\main\\java\\oopwj\\lecturer.txt", "Lecturer");
        AcademicList.clearSelection();

        JOptionPane.showMessageDialog(this, "Lecturer updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignLecturerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AssignLecturerPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AcademicList;
    private javax.swing.JTable LecturerList;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchAcademic;
    private javax.swing.JTextField searchLecturer;
    // End of variables declaration//GEN-END:variables
}
