/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package oopwj.AdministrativeStaff;

import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kwany
 */
public class RemoveModule extends javax.swing.JDialog {

    private final String classroom;
    private final String classroomId;
    private final Date date;
    /**
     * Creates new form RemoveModule
     * @param parent
     * @param modal
     * @param selectedDate
     * @param selectedClassroomId
     * @param selectedClassroom
     */
    public RemoveModule(java.awt.Frame parent, boolean modal, Date selectedDate, String selectedClassroomId, String selectedClassroom) {
        super(parent, modal);
        this.classroom = selectedClassroom;
        this.classroomId = selectedClassroomId;
        this.date = selectedDate;
        
        initComponents();
        setLocationRelativeTo(null);
        
        loadTable(date);
    }
    
    private void loadTable(Date selectedDate) {
    DefaultTableModel model = (DefaultTableModel) removeTable.getModel();
    model.setRowCount(0);

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String dateStr = sdf.format(selectedDate);

    File scheduleFile = new File("src\\main\\java\\oopwj\\class_schedule.txt");

    try (BufferedReader br = new BufferedReader(new FileReader(scheduleFile))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data.length >= 6 && data[0].equals(classroomId) && data[2].equals(dateStr)) {
                model.addRow(new Object[]{
                    classroom,
                    data[1],
                    data[2],
                    data[4],
                    data[5]
                });
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Failed to load schedule.");
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        removeTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        removeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Classroom", "Module ID", "Date", "Start Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        removeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(removeTable);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemove))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRemove))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int row = removeTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a module to remove.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) removeTable.getModel();
        String moduleId = (String) model.getValueAt(row, 1);
        String dateTable = (String) model.getValueAt(row, 2);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove module " + moduleId + " on " + dateTable + "?",
                "Confirm Remove",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        File scheduleFile = new File("src\\main\\java\\oopwj\\class_schedule.txt");
        File tempFile = new File("src\\main\\java\\oopwj\\class_schedule_temp.txt");

        try (BufferedReader br = new BufferedReader(new FileReader(scheduleFile));
             BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length >= 6 && data[0].equals(classroomId) && data[1].equals(moduleId) && data[2].equals(dateTable)) {
                    continue;
                }
                bw.write(line);
                bw.newLine();
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to remove module.");
            return;
        }

        if (!scheduleFile.delete() || !tempFile.renameTo(scheduleFile)) {
            JOptionPane.showMessageDialog(this, "Failed to update schedule file.");
            return;
        }

        JOptionPane.showMessageDialog(this, "Module removed successfully.");

        loadTable(this.date);
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable removeTable;
    // End of variables declaration//GEN-END:variables
}
