/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package oopwj.AdministrativeStaff;

import java.awt.HeadlessException;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author kwany
 */
public class UpdateUserPage extends javax.swing.JDialog {

    /**
     * Creates new form UpdateUserPage
     * @param parent
     * @param modal
     * @param username
     * @param userId
     * @param password
     * @param email
     * @param role
     */
    
    private final String originalUsername;
    private final String originalId;
    
    public UpdateUserPage(java.awt.Frame parent, boolean modal, String username, String userId, String password, String email, String role) {
        super(parent, modal);
        initComponents();
        setSize(448, 347);
        setLocationRelativeTo(null);
        txtEmail.setEditable(false);
        txtEmail.setFocusable(false);
        
        txtUsername.setText(username);
        txtId.setText(userId);
        txtPassword.setText(password);
        txtEmail.setText(email);
        
        
        switch (role) {
            case "Student" -> radioStudent.setSelected(true);
            case "Lecturer" -> radioLecturer.setSelected(true);
            case "Academic Leader" -> radioAcademic.setSelected(true);
            case "Admin" -> radioAdmin.setSelected(true);
        }
        
        ButtonGroup roleGroup = new ButtonGroup();
        roleGroup.add(radioStudent);
        roleGroup.add(radioLecturer);
        roleGroup.add(radioAcademic);
        roleGroup.add(radioAdmin);
        
        char Bullet = '\u2022';
        chkPassword.addActionListener(e -> {
            if (chkPassword.isSelected()) txtPassword.setEchoChar((char) 0);
            else txtPassword.setEchoChar(Bullet);
        });
        
        originalUsername = username;
        originalId = userId;
        
        txtId.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateEmailField();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateEmailField();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateEmailField();
            }
        });
    }
    
    private String getFileByRole(String role) {
    switch (role) {
        case "Student" -> {
            return "student.txt";
            }
        case "Admin" -> {
            return "admin.txt";
            }
        case "Lecturer" -> {
            return "lecturer.txt";
            }
        case "Academic Leader" -> {
            return "academicLeader.txt";
            }
        default -> throw new IllegalArgumentException("Unknown role");
    }
}
    
    private void updateEmailField() {
    String userId = txtId.getText().trim();

    if (!userId.isEmpty()) {
        txtEmail.setText(userId + "@mail.apu.edu.my");
    } else {
        txtEmail.setText("");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        radioStudent = new javax.swing.JRadioButton();
        radioLecturer = new javax.swing.JRadioButton();
        radioAcademic = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        chkPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update User");
        setPreferredSize(new java.awt.Dimension(448, 347));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("User ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Role:");

        radioStudent.setText("Student");

        radioLecturer.setText("Lecturer");

        radioAcademic.setText("Academic Leader");

        radioAdmin.setText("Admin");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        chkPassword.setText("Show Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(radioAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAcademic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsername)
                        .addComponent(txtId)
                        .addComponent(txtPassword)
                        .addComponent(txtEmail)
                        .addComponent(radioStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPassword)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radioStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAcademic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean isValid;
        String username = txtUsername.getText().trim();
        String userId = txtId.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String email = txtEmail.getText().trim();

        String role = "";
        if (radioStudent.isSelected()) role = "Student";
        else if (radioLecturer.isSelected()) role = "Lecturer";
        else if (radioAcademic.isSelected()) role = "Academic Leader";
        else if (radioAdmin.isSelected()) role = "Admin";

        
        if (username.isEmpty() || userId.isEmpty() || password.isEmpty() || email.isEmpty() || role.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields and select a role.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        switch (role) {
            case "Student" -> isValid = userId.matches("^S\\d{3}$");
            case "Lecturer" -> isValid = userId.matches("^L\\d{3}$");
            case "Academic Leader" -> isValid = userId.matches("^AC\\d{3}$");
            case "Admin" -> isValid = userId.matches("^A\\d{3}$");
            default -> isValid = false;
        }

        if (!isValid) {
            JOptionPane.showMessageDialog(this,
                "Invalid User ID format!\n\n"
                + "Student: S001\n"
                + "Lecturer: L001\n"
                + "Academic Leader: AC001\n"
                + "Admin: A001",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        String fileName = getFileByRole(role);

        try {
            File inputFile = new File(fileName);
            File tempFile = new File("users_temp.txt");

            try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
                 BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(",");
                    if (parts[1].equals(originalUsername) && parts[0].equals(originalId)) {
                        if ("Lecturer".equals(role) && parts.length >= 5) {
                            writer.write(userId + "," + username + "," + password + "," + email + "," + parts[4]);
                        } else {
                            writer.write(userId + "," + username + "," + password + "," + email);
                        }
                    } else {
                        writer.write(line);
                    }
                    writer.newLine();
                }
            }

            if (!inputFile.delete() || !tempFile.renameTo(inputFile)) {
                throw new IOException("Failed to update user in file.");
            }

            JOptionPane.showMessageDialog(this, "User updated successfully!", 
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (HeadlessException | IOException ex) {
            JOptionPane.showMessageDialog(this, "Error updating user: " + ex.getMessage(), 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioAcademic;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioLecturer;
    private javax.swing.JRadioButton radioStudent;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
