/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package oopwj.AdministrativeStaff;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.*;
import javax.swing.*;
import java.text.*;
import java.util.*;

/**
 *
 * @author kwany
 */
public class UpdateSchedule extends javax.swing.JDialog {

    private final String originalClassId;
    private final String originalDate;
    private final String originalStart;
    private final String originalEnd;
    /**
     * Creates new form UpdateSchedule
     * @param parent
     * @param modal
     * @param classId
     * @param moduleId
     * @param date
     * @param start
     * @param end
     */
    public UpdateSchedule(java.awt.Frame parent, boolean modal, String classId, String moduleId, String date, String start, String end) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        this.originalClassId = classId;
        this.originalDate = date;
        this.originalStart = start;
        this.originalEnd = end;
        
        loadClassrooms(classId);
        txtModule.setText(moduleId);
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date parsedDate = sdf.parse(date);
            dateChoose.setDate(parsedDate);

            // set day name
            SimpleDateFormat dayFmt = new SimpleDateFormat("EEEE");
            txtDay.setText(dayFmt.format(parsedDate));

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format.");
        }
        
        setTime(spinMin, start);
        setTime(spinMax, end);
        
        addHoverEffect(btnUpdate,new Color(70,130,180),new Color(100,149,237));
        addHoverEffect(btnBack,new Color(200,200,200),new Color(170,170,170));
    }
    
    private void addHoverEffect(JButton btn, Color normal, Color hover) {
        btn.setOpaque(true);
        btn.setContentAreaFilled(true);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);

        btn.setBackground(normal);
        btn.setForeground(Color.WHITE);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(normal);
            }
        });
    }
    
    private void setTime(JSpinner spinner, String timeStr) {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        spinner.setValue(sdf.parse(timeStr));
    } catch (ParseException e) {
        spinner.setValue(new Date());
    }
}
    
    private void loadClassrooms(String currentClassId) {
    cboClassroom.removeAllItems();

    File classFile = new File("src\\main\\java\\oopwj\\Data\\class.txt");

    try (BufferedReader br = new BufferedReader(new FileReader(classFile))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            String classId = data[0];
            String className = data[1];

            cboClassroom.addItem(classId + " - " + className);

            if (classId.equals(currentClassId)) {
                cboClassroom.setSelectedItem(classId + " - " + className);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Failed to load classrooms.");
    }
}
    
    private String getDayFromDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE");
        return sdf.format(date);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserPanel1 = new com.toedter.calendar.demo.DateChooserPanel();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;

                GradientPaint gp = new GradientPaint(
                    0, 0, new Color(220, 240, 255),
                    0, getHeight(), new Color(245, 250, 255)
                );

                g2.setPaint(gp);
                g2.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        txtDay = new javax.swing.JTextField();
        spinMin = new JSpinner(new SpinnerDateModel())
        ;
        JSpinner.DateEditor startEditor = new JSpinner.DateEditor(spinMin, "HH:mm");
        spinMin.setEditor(startEditor);
        spinMax = new JSpinner(new SpinnerDateModel())
        ;
        JSpinner.DateEditor endEditor = new JSpinner.DateEditor(spinMax, "HH:mm");
        spinMax.setEditor(endEditor);
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dateChoose = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cboClassroom = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModule = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Schedule Page");

        txtDay.setFocusable(false);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Class ID:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Module ID:");

        dateChoose.setMinSelectableDate(new Date());
        dateChoose.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChoosePropertyChange(evt);
            }
        });

        jLabel3.setText("Date:");

        cboClassroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Day:");

        jLabel5.setText("Start Time:");

        jLabel6.setText("End Time:");

        txtModule.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinMax)
                            .addComponent(dateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModule)
                            .addComponent(txtDay)
                            .addComponent(spinMin)
                            .addComponent(cboClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dateChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnUpdate))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String selected = cboClassroom.getSelectedItem().toString();
        String newClassId = selected.split(" - ")[0];

        Date newDateObj = dateChoose.getDate();
        if (newDateObj == null) {
            JOptionPane.showMessageDialog(this, "Please select a date.");
            return;
        }

        SimpleDateFormat dateFmt = new SimpleDateFormat("dd/MM/yyyy");
        String newDate = dateFmt.format(newDateObj);

        Date newStart = (Date) spinMin.getValue();
        Date newEnd = (Date) spinMax.getValue();

        if (!newStart.before(newEnd)) {
            JOptionPane.showMessageDialog(this,
                    "Start time must be before end time.");
            return;
        }

        SimpleDateFormat timeFmt = new SimpleDateFormat("HH:mm");
        String newStartStr = timeFmt.format(newStart);
        String newEndStr = timeFmt.format(newEnd);

        File inputFile = new File("src\\main\\java\\oopwj\\Data\\class_schedule.txt");
        File tempFile = new File("src\\main\\java\\oopwj\\Data\\class_schedule_temp.txt");

        boolean conflictFound = false;

        try (BufferedReader br = new BufferedReader(new FileReader(inputFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");

                String classId = data[0];
                String date = data[2];

                if (!classId.equals(newClassId) || !date.equals(newDate))
                    continue;

                boolean isOriginal =
                        classId.equals(originalClassId) &&
                        date.equals(originalDate) &&
                        data[4].equals(originalStart) &&
                        data[5].equals(originalEnd);

                if (isOriginal) continue;

                Date existingStart = timeFmt.parse(data[4]);
                Date existingEnd = timeFmt.parse(data[5]);

                if (!newEnd.before(existingStart) &&
                    !newStart.after(existingEnd)) {
                    conflictFound = true;
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to validate schedule.");
            return;
        }

        if (conflictFound) {
            JOptionPane.showMessageDialog(this,
                    "Schedule conflict detected.\n" +
                    "The selected classroom is not available at this time.");
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(inputFile));
             BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile))) {

            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");

                boolean isTarget =
                        data[0].equals(originalClassId) &&
                        data[2].equals(originalDate) &&
                        data[4].equals(originalStart) &&
                        data[5].equals(originalEnd);

                if (isTarget) {
                    bw.write(
                            newClassId + "," +
                            data[1] + "," +
                            newDate + "," +
                            txtDay.getText() + "," +
                            newStartStr + "," +
                            newEndStr
                    );
                } else {
                    bw.write(line);
                }
                bw.newLine();
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Update failed.");
            return;
        }

        inputFile.delete();
        tempFile.renameTo(inputFile);

        JOptionPane.showMessageDialog(this, "Schedule updated successfully.");
        dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void dateChoosePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChoosePropertyChange
        Date selectedDate = dateChoose.getDate();
        if (selectedDate != null) {
            txtDay.setText(getDayFromDate(selectedDate));
        }
    }//GEN-LAST:event_dateChoosePropertyChange

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboClassroom;
    private com.toedter.calendar.JDateChooser dateChoose;
    private com.toedter.calendar.demo.DateChooserPanel dateChooserPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinMax;
    private javax.swing.JSpinner spinMin;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtModule;
    // End of variables declaration//GEN-END:variables
}
