/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Assessments extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Assessments.class.getName());
    private String currentDataType = null; // Track which data is currently displayed
    private String lecturerID;
    private Lecturer_menu parentWindow;
    private Map<String, String> lecturerModules = new HashMap<>(); // moduleId -> moduleName
    private List<String> originalQuizLines = new ArrayList<>(); // Store original lines from question.txt

    /**
     * Creates new form Assessments
     */
    public Assessments() {
        this(null, null);
    }
    
    public Assessments(String lecturerID, Lecturer_menu parentWindow) {
        this.lecturerID = lecturerID;
        this.parentWindow = parentWindow;
        loadLecturerModules(); // Load modules assigned to this lecturer
        initComponents();
        setupTable();
        setupSearchField();
        displayAssignedModules(); // Show assigned modules to the lecturer
        loadQuizData();
        currentDataType = "quiz";
        QuizButton.addActionListener(this::QuizButtonActionPerformed);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jButton4.addActionListener(this::jButton4ActionPerformed);
    }
    
    private void setupSearchField() {
        jTextField1.setForeground(java.awt.Color.GRAY);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().equals("Search")) {
                    jTextField1.setText("");
                    jTextField1.setForeground(java.awt.Color.BLACK);
                }
            }
            
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText("Search");
                    jTextField1.setForeground(java.awt.Color.GRAY);
                }
            }
        });
    }
    
    private void setupTable() {
        String[] columnNames = {};
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            columnNames
        ));
        centerAlignTable(jTable2);
    }
    
    private void centerAlignTable(javax.swing.JTable table) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            table.getColumnModel().getColumn(i).getHeaderRenderer();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        QuizButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        QuizButton.setText("Quiz");

        jButton1.setText("Back");

        jButton2.setText("Add");

        jScrollPane2.setViewportView(jTable2);

        jTextField1.setText("Search");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton3.setText("Search");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Edit");

        jButton5.setText("Delete");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuizButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(133, 133, 133)
                        .addComponent(jButton4)
                        .addGap(70, 70, 70)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuizButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        performSearch();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        performSearch();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int[] selectedRows = jTable2.getSelectedRows();
        
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmation = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete " + selectedRows.length + " row(s)?", 
            "Confirm Deletion", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmation == JOptionPane.YES_OPTION) {
            deleteSelectedRows(selectedRows);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void deleteSelectedRows(int[] selectedRows) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        // Collect the indices to delete in descending order
        java.util.Arrays.sort(selectedRows);
        
        // Create a set of original line indices to delete
        java.util.Set<Integer> linesToDelete = new java.util.HashSet<>();
        for (int selectedRow : selectedRows) {
            if (selectedRow >= 0 && selectedRow < model.getRowCount()) {
                linesToDelete.add(selectedRow);
            }
        }
        
        // Remove from table (in reverse order)
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            model.removeRow(selectedRows[i]);
        }
        
        // Update the file with remaining data
        if ("quiz".equals(currentDataType)) {
            updateQuizFile(linesToDelete);
        }
        
        JOptionPane.showMessageDialog(this, "Row(s) deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void updateQuizFile(java.util.Set<Integer> linesToDelete) {
        String projectRoot = System.getProperty("user.dir");
        File quizFile = new File(projectRoot, "src\\main\\java\\oopwj\\question.txt");
        
        try {
            // First, collect remaining lines and renumber them
            Map<String, Integer> questionCounters = new HashMap<>(); // Key: "QuizID|ModuleID", Value: counter
            List<String> updatedLines = new ArrayList<>();
            
            for (int i = 0; i < originalQuizLines.size(); i++) {
                if (!linesToDelete.contains(i)) {
                    String line = originalQuizLines.get(i);
                    String[] fields = line.split(",", -1); // Split by comma, keep empty fields
                    
                    if (fields.length >= 3) {
                        // Format: QuestionID[0], QuizID[1], ModuleID[2], ...
                        String quizID = fields[1].trim();
                        String moduleID = fields[2].trim();
                        String key = quizID + "|" + moduleID;
                        
                        // Increment counter for this quiz/module combination
                        int newCount = questionCounters.getOrDefault(key, 0) + 1;
                        questionCounters.put(key, newCount);
                        
                        // Create new question ID with leading zeros
                        String newQuestionID = String.format("Q%03d", newCount);
                        
                        // Replace the question ID in the first field
                        fields[0] = newQuestionID;
                        
                        // Reconstruct the line with the new question ID
                        String updatedLine = String.join(",", fields);
                        updatedLines.add(updatedLine);
                    }
                }
            }
            
            // Write updated lines to file
            try (java.io.FileWriter fw = new java.io.FileWriter(quizFile)) {
                for (String line : updatedLines) {
                    fw.write(line + "\n");
                }
            }
            
            // Update originalQuizLines for future operations
            originalQuizLines.clear();
            originalQuizLines.addAll(updatedLines);
            
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error updating question.txt: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void performSearch() {
        String searchTerm = jTextField1.getText().trim();

        if (searchTerm.isEmpty() || searchTerm.equalsIgnoreCase("Search")) {
            JOptionPane.showMessageDialog(this, "Please enter a search term", "Search", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        List<Object[]> matchingRows = new ArrayList<>();
        String[] columnNames = {};

        // Search in question.txt
        matchingRows.addAll(searchInFile("src\\main\\java\\oopwj\\question.txt", searchTerm, true));
        if (!matchingRows.isEmpty()) {
            columnNames = new String[]{"Question ID", "Question", "Type", "A", "B", "C", "D", "Answer"};
        }

        DefaultTableModel model = new DefaultTableModel(matchingRows.toArray(new Object[0][]), columnNames);
        jTable2.setModel(model);
        centerAlignTable(jTable2);
    }
    
    private List<Object[]> searchInFile(String filePath, String searchTerm, boolean isQuiz) {
        List<Object[]> results = new ArrayList<>();
        String projectRoot = System.getProperty("user.dir");
        File file = new File(projectRoot, filePath);

        if (!file.exists()) {
            return results;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] fields = parseCSV(line);

                // Check if any field contains the search term
                boolean matches = false;
                for (String field : fields) {
                    if (field.toLowerCase().contains(searchTerm.toLowerCase())) {
                        matches = true;
                        break;
                    }
                }

                if (matches) {
                    if (isQuiz) {
                        // Check if the question is subjective or objective
                        if (fields.length == 6) {
                            // Subjective question: [Module ID, Module Name, Question ID, Question, Type]
                            results.add(new Object[]{fields[2], fields[3], fields[5], "-", "-", "-", "-"});
                        } else if (fields.length == 10) {
                            // Objective question: [Module ID, Module Name, Question ID, Question, A, B, C, D, Answer, Type]
                            results.add(new Object[]{fields[2], fields[3], fields[9], fields[4], fields[5], fields[6], fields[7], fields[8]});
                        }
                    }
                }
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        return results;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (parentWindow != null) {
            parentWindow.setVisible(true);
        } else {
            new Lecturer_menu(lecturerID).setVisible(true);
        }
        this.dispose();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentDataType == null) {
            JOptionPane.showMessageDialog(this, "Please click a button above (Quiz) before clicking Add", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if ("quiz".equals(currentDataType)) {
            new Quiz(lecturerID, this).setVisible(true);
        }
        this.dispose();
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = jTable2.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (currentDataType == null) {
            JOptionPane.showMessageDialog(this, "Please click a button above (Quiz) to view data", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if ("quiz".equals(currentDataType)) {
            editQuizRow(selectedRow);
        }
    }
    
    private void editQuizRow(int selectedRow) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        String question = model.getValueAt(selectedRow, 1).toString();
        String answerA = model.getValueAt(selectedRow, 2).toString();
        String answerB = model.getValueAt(selectedRow, 3).toString();
        String answerC = model.getValueAt(selectedRow, 4).toString();
        String answerD = model.getValueAt(selectedRow, 5).toString();
        String correctAnswer = model.getValueAt(selectedRow, 6).toString();
        
        Quiz quizForm = new Quiz(question, answerA, answerB, answerC, answerD, correctAnswer);
        quizForm.setVisible(true);
        this.dispose();
    }
    
    private void QuizButtonActionPerformed(java.awt.event.ActionEvent evt) {
        currentDataType = "quiz";
        loadQuizData();
    }
    
    private void loadLecturerModules() {
        lecturerModules.clear();
        
        if (lecturerID == null) {
            return; // If no lecturer ID, don't filter
        }
        
        String projectRoot = System.getProperty("user.dir");
        File modulesFile = new File(projectRoot, "src\\main\\java\\oopwj\\modules.txt");
        
        if (!modulesFile.exists()) {
            logger.log(java.util.logging.Level.WARNING, "modules.txt not found");
            return;
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(modulesFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty()) {
                    String[] parts = trimmed.split(",");
                    if (parts.length >= 4) {
                        String moduleId = parts[0].trim();
                        String moduleName = parts[1].trim();
                        String assignedLecturerId = parts[3].trim();
                        
                        // Check if this module is assigned to the current lecturer
                        if (assignedLecturerId.equals(lecturerID)) {
                            lecturerModules.put(moduleId, moduleName);
                        }
                    }
                }
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading modules", ex);
        }
        
        // Log the modules for debugging
        if (lecturerModules.isEmpty()) {
            logger.log(java.util.logging.Level.INFO, "No modules assigned to lecturer: " + lecturerID);
        } else {
            logger.log(java.util.logging.Level.INFO, "Lecturer " + lecturerID + " has " + lecturerModules.size() + " modules");
        }
    }
    
    private void displayAssignedModules() {
        if (lecturerID == null) {
            return;
        }
        
        if (lecturerModules.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "You are not assigned to any modules yet.", 
                "Assigned Modules", 
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            StringBuilder message = new StringBuilder("Your Assigned Modules:\n\n");
            for (Map.Entry<String, String> entry : lecturerModules.entrySet()) {
                message.append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
            }
            JOptionPane.showMessageDialog(this, 
                message.toString(), 
                "Assigned Modules", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void loadQuizData() {
        String projectRoot = System.getProperty("user.dir");
        File quizFile = new File(projectRoot, "src\\main\\java\\oopwj\\question.txt");

        // Load total marks per quiz
        Map<String, String> quizMarks = loadQuizMarks(projectRoot);

        // Update column names to ModuleID, QuizID, QuestionID, Question Type, Total Marks
        String[] columnNames = {"ModuleID", "QuizID", "QuestionID", "Question Type", "Total Marks"};
        List<Object[]> rows = new ArrayList<>();
        originalQuizLines.clear(); // Clear previous data

        if (quizFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(quizFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String[] fields = parseCSV(line);
                    // Store the original line
                    originalQuizLines.add(line);
                    
                    // New format: QuestionID[0], QuizID[1], ModuleID[2], Question[3], Options[4-7], CorrectAnswer[8], Type[9]
                    if (fields.length == 10) { // Objective question with QuizID
                        String quizID = fields[1];
                        String totalMarks = quizMarks.getOrDefault(quizID, "1");
                        rows.add(new Object[]{fields[2], quizID, fields[0], fields[9], totalMarks});
                    } else if (fields.length == 5) { // Subjective question with QuizID
                        String quizID = fields[1];
                        String totalMarks = quizMarks.getOrDefault(quizID, "1");
                        rows.add(new Object[]{fields[2], quizID, fields[0], fields[4], totalMarks});
                    }
                }
            } catch (IOException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error reading question.txt: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Update the table model with the new data
        DefaultTableModel model = new DefaultTableModel(rows.toArray(new Object[0][]), columnNames);
        jTable2.setModel(model);
        centerAlignTable(jTable2);
    }
    
    private Map<String, String> loadQuizMarks(String projectRoot) {
        Map<String, String> quizMarks = new HashMap<>();
        File marksFile = new File(projectRoot, "src\\main\\java\\oopwj\\TotalQuizMark.txt");
        
        if (marksFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(marksFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String[] fields = parseCSV(line);
                    if (fields.length >= 3) {
                        // Format: ModuleID[0], QuizID[1], TotalMarks[2]
                        quizMarks.put(fields[1], fields[2]);
                    }
                }
            } catch (IOException ex) {
                logger.log(java.util.logging.Level.WARNING, "Error reading TotalQuizMark.txt", ex);
            }
        }
        
        return quizMarks;
    }
    
    private String[] parseCSV(String line) {
        List<String> fields = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        boolean inQuotes = false;
        
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            
            if (c == '"') {
                inQuotes = !inQuotes;
            } else if (c == ',' && !inQuotes) {
                fields.add(current.toString().trim().replaceAll("^\"|\"$", ""));
                current = new StringBuilder();
            } else {
                current.append(c);
            }
        }
        
        fields.add(current.toString().trim().replaceAll("^\"|\"$", ""));
        return fields.toArray(new String[0]);
    }

    private String[] normalizeQuizFields(String[] fields) {
        if (fields.length == 8) {
            return Arrays.copyOfRange(fields, 1, 8);
        }
        return fields;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Assessments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuizButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
