/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author User
 */
public class Feedback extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Feedback.class.getName());
    
    private String moduleID;
    private String quizID;
    private String studentID;
    private String lecturerID;

    /**
     * Creates new form Feedback
     */
    public Feedback() {
        initComponents();
    }
    
    /**
     * Creates new form Feedback with parameters
     */
    public Feedback(String moduleID, String quizID, String studentID, String lecturerID) {
        this.moduleID = moduleID;
        this.quizID = quizID;
        this.studentID = studentID;
        this.lecturerID = lecturerID;
        
        initComponents();
        setLocationRelativeTo(null);
        
        // Load existing feedback if available
        loadExistingFeedback();
        
        // Attach action listener to Save button
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        // Attach action listener to Back button
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Type your Feedback:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Save");

        jButton2.setText("Back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Get feedback from text area
        String feedback = jTextArea1.getText();
        
        if (feedback.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter feedback before saving.",
                "Empty Feedback",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update feedback in FinalGrade.txt
        String projectRoot = System.getProperty("user.dir");
        String finalGradeFilePath = projectRoot + "/src/main/java/oopwj/FinalGrade.txt";
        
        if (!updateFeedbackInFile(finalGradeFilePath, feedback)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Could not find grade record for this student.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Feedback saved successfully!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        Grade_Assessment gradeAssessment;
        if (lecturerID != null && !lecturerID.isEmpty()) {
            gradeAssessment = new Grade_Assessment(lecturerID);
        } else {
            gradeAssessment = new Grade_Assessment();
        }
        gradeAssessment.setLocationRelativeTo(null);
        gradeAssessment.setVisible(true);
        this.dispose();
    }
    
    /**
     * Updates the feedback in FinalGrade.txt for the given student
     */
    private boolean updateFeedbackInFile(String finalGradeFilePath, String feedback) {
        java.io.File finalGradeFile = new java.io.File(finalGradeFilePath);
        if (!finalGradeFile.exists()) {
            logger.log(java.util.logging.Level.WARNING, "FinalGrade.txt not found");
            return false;
        }
        
        java.util.List<String> lines = new java.util.ArrayList<>();
        boolean found = false;
        
        try (BufferedReader br = new BufferedReader(new FileReader(finalGradeFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                    lines.add(line);
                    continue;
                }
                
                String[] parts = trimmedLine.split(",", 6); // Split into max 6 parts to preserve feedback quotes
                if (parts.length >= 5) {
                    String studentIDFromFile = parts[0].trim();
                    String moduleIDFromFile = parts[1].trim();
                    String quizIDFromFile = parts[2].trim();
                    String markFromFile = parts[3].trim();
                    String gradeFromFile = parts[4].trim();
                    
                    // Match this student's quiz
                    if (studentIDFromFile.equals(studentID) &&
                        moduleIDFromFile.equals(moduleID) &&
                        quizIDFromFile.equals(quizID)) {
                        
                        // Reconstruct line with new feedback
                        // Format: StudentID,ModuleID,QuizID,Mark,Grade,"Feedback"
                        String formattedFeedback = formatFeedbackField(feedback);
                        String updatedLine = studentID + "," + moduleID + "," + quizID + "," +
                                           markFromFile + "," + gradeFromFile + "," + formattedFeedback;
                        lines.add(updatedLine);
                        found = true;
                        System.out.println("Updated feedback for student: " + studentID);
                    } else {
                        lines.add(trimmedLine);
                    }
                } else {
                    lines.add(trimmedLine);
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading FinalGrade.txt: " + e.getMessage());
            return false;
        }
        
        // Write back to file
        if (found) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(finalGradeFile))) {
                for (String line : lines) {
                    bw.write(line);
                    bw.newLine();
                }
                System.out.println("Saved feedback to FinalGrade.txt");
            } catch (IOException e) {
                System.err.println("Error writing to FinalGrade.txt: " + e.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error saving feedback: " + e.getMessage(),
                    "File Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        return found;
    }

    private String formatFeedbackField(String feedback) {
        if (feedback == null) {
            return "\"\"";
        }
        String trimmed = feedback.trim();
        String escaped = trimmed.replace("\"", "\"\"");
        return "\"" + escaped + "\"";
    }
    
    /**
     * Loads existing feedback from FinalGrade.txt and displays it in the text area
     */
    private void loadExistingFeedback() {
        String projectRoot = System.getProperty("user.dir");
        String finalGradeFilePath = projectRoot + "/src/main/java/oopwj/FinalGrade.txt";
        
        java.io.File finalGradeFile = new java.io.File(finalGradeFilePath);
        if (!finalGradeFile.exists()) {
            logger.log(java.util.logging.Level.WARNING, "FinalGrade.txt not found");
            return;
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(finalGradeFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                    continue;
                }
                
                String[] parts = trimmedLine.split(",", 6);
                if (parts.length >= 6) {
                    String studentIDFromFile = parts[0].trim();
                    String moduleIDFromFile = parts[1].trim();
                    String quizIDFromFile = parts[2].trim();
                    
                    // Match this student's quiz
                    if (studentIDFromFile.equals(studentID) &&
                        moduleIDFromFile.equals(moduleID) &&
                        quizIDFromFile.equals(quizID)) {
                        
                        // Extract feedback (6th column)
                        String feedbackField = parts[5].trim();
                        // Remove surrounding quotes and unescape
                        String feedback = feedbackField;
                        if (feedback.startsWith("\"") && feedback.endsWith("\"")) {
                            feedback = feedback.substring(1, feedback.length() - 1);
                            feedback = feedback.replace("\"\"", "\"");
                        }
                        
                        jTextArea1.setText(feedback);
                        System.out.println("Loaded feedback for student: " + studentID);
                        return;
                    }
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading FinalGrade.txt: " + e.getMessage());
            logger.log(java.util.logging.Level.WARNING, "Error loading feedback: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Feedback().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
