/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JButton;

/**
 *
 * @author User
 */
public class Feedback extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Feedback.class.getName());
    
    private String moduleID;
    private String quizID;
    private String studentID;
    private String lecturerID;
    private boolean isQuizSetFeedback = false;
    private javax.swing.JFrame parentWindow = null;

    /**
     * Creates new form Feedback
     */
    public Feedback() {
        initComponents();
    }
    
    /**
     * Creates new form Feedback with parameters (for student feedback)
     */
    public Feedback(String moduleID, String quizID, String studentID, String lecturerID) {
        this.moduleID = moduleID;
        this.quizID = quizID;
        this.studentID = studentID;
        this.lecturerID = lecturerID;
        this.isQuizSetFeedback = false;
        
        initComponents();
        setLocationRelativeTo(null);
        
        // Load existing feedback if available
        loadExistingFeedback();
        
        // Attach action listener to Save button
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        // Attach action listener to Back button
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
        addHoverEffect(jButton1,new Color(70,130,180),new Color(70,130,180));
        addHoverEffect(jButton2,new Color(220,80,80),new Color(220,80,80));
    }
    
    /**
     * Creates new form Feedback for quiz set feedback (no specific student)
     */
    public Feedback(String moduleID, String quizID, String lecturerID, boolean isQuizSetFeedback) {
        this.moduleID = moduleID;
        this.quizID = quizID;
        this.lecturerID = lecturerID;
        this.isQuizSetFeedback = isQuizSetFeedback;
        this.studentID = null;
        this.parentWindow = null;
        
        initComponents();
        setLocationRelativeTo(null);
        
        // Load existing quiz-set feedback if available
        if (isQuizSetFeedback) {
            loadExistingQuizSetFeedback();
        }
        
        // Attach action listener to Save button
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        // Attach action listener to Back button
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
    }
    
    /**
     * Creates new form Feedback for quiz set feedback with parent window reference
     */
    public Feedback(String moduleID, String quizID, String lecturerID, boolean isQuizSetFeedback, javax.swing.JFrame parentWindow) {
        this.moduleID = moduleID;
        this.quizID = quizID;
        this.lecturerID = lecturerID;
        this.isQuizSetFeedback = isQuizSetFeedback;
        this.studentID = null;
        this.parentWindow = parentWindow;
        
        initComponents();
        setLocationRelativeTo(null);
        
        // Load existing quiz-set feedback if available
        if (isQuizSetFeedback) {
            loadExistingQuizSetFeedback();
        }
        
        // Attach action listener to Save button
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));
        // Attach action listener to Back button
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));
    }

    private void addHoverEffect(JButton btn, Color normal, Color hover) {
        btn.setOpaque(true);
        btn.setContentAreaFilled(true);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);

        btn.setBackground(normal);
        btn.setForeground(Color.WHITE);

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(hover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(normal);
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g;

                GradientPaint gp = new GradientPaint(
                    0, 0, new Color(230, 240, 255),
                    0, getHeight(), new Color(245, 247, 250)
                );

                g2.setPaint(gp);
                g2.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Type your Feedback:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Save");

        jButton2.setText("Back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Get feedback from text area
        String feedback = jTextArea1.getText();
        
        if (feedback.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter feedback before saving.",
                "Empty Feedback",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Handle based on feedback type
        if (isQuizSetFeedback) {
            // Save quiz set feedback
            if (!saveQuizSetFeedback(feedback)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Could not save quiz set feedback.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Refresh quiz sets table in parent window if available
            if (parentWindow != null && parentWindow instanceof oopwj.Lecturer.Assessments) {
                ((oopwj.Lecturer.Assessments) parentWindow).refreshTableData();
            }
        } else {
            // Save student feedback
            String projectRoot = System.getProperty("user.dir");
            String finalGradeFilePath = projectRoot + "\\src\\main\\java\\oopwj\\data\\FinalGrade.txt";
            
            if (!updateFeedbackInFile(finalGradeFilePath, feedback)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Could not find grade record for this student.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Feedback saved successfully!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // If there's a parent window (Assessments), return to it
        if (parentWindow != null) {
            parentWindow.setVisible(true);
            this.dispose();
        } else {
            // Otherwise, navigate to Grade_Assessment (original behavior)
            Grade_Assessment gradeAssessment;
            if (lecturerID != null && !lecturerID.isEmpty()) {
                gradeAssessment = new Grade_Assessment(lecturerID);
            } else {
                gradeAssessment = new Grade_Assessment();
            }
            gradeAssessment.setLocationRelativeTo(null);
            gradeAssessment.setVisible(true);
            this.dispose();
        }
    }
    
    /**
     * Updates the feedback in FinalGrade.txt for the given student
     */
    private boolean updateFeedbackInFile(String finalGradeFilePath, String feedback) {
        java.io.File finalGradeFile = new java.io.File(finalGradeFilePath);
        if (!finalGradeFile.exists()) {
            logger.log(java.util.logging.Level.WARNING, "FinalGrade.txt not found");
            return false;
        }
        
        java.util.List<String> lines = new java.util.ArrayList<>();
        boolean found = false;
        
        try (BufferedReader br = new BufferedReader(new FileReader(finalGradeFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                    lines.add(line);
                    continue;
                }
                
                String[] parts = trimmedLine.split(",", 6); // Split into max 6 parts to preserve feedback quotes
                if (parts.length >= 5) {
                    String studentIDFromFile = parts[0].trim();
                    String moduleIDFromFile = parts[1].trim();
                    String quizIDFromFile = parts[2].trim();
                    String markFromFile = parts[3].trim();
                    String gradeFromFile = parts[4].trim();
                    
                    // Match this student's quiz
                    if (studentIDFromFile.equals(studentID) &&
                        moduleIDFromFile.equals(moduleID) &&
                        quizIDFromFile.equals(quizID)) {
                        
                        // Reconstruct line with new feedback
                        // Format: StudentID,ModuleID,QuizID,Mark,Grade,"Feedback"
                        String formattedFeedback = formatFeedbackField(feedback);
                        String updatedLine = studentID + "," + moduleID + "," + quizID + "," +
                                           markFromFile + "," + gradeFromFile + "," + formattedFeedback;
                        lines.add(updatedLine);
                        found = true;
                        System.out.println("Updated feedback for student: " + studentID);
                    } else {
                        lines.add(trimmedLine);
                    }
                } else {
                    lines.add(trimmedLine);
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading FinalGrade.txt: " + e.getMessage());
            return false;
        }
        
        // Write back to file
        if (found) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(finalGradeFile))) {
                for (String line : lines) {
                    bw.write(line);
                    bw.newLine();
                }
                System.out.println("Saved feedback to FinalGrade.txt");
            } catch (IOException e) {
                System.err.println("Error writing to FinalGrade.txt: " + e.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error saving feedback: " + e.getMessage(),
                    "File Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        return found;
    }

    private String formatFeedbackField(String feedback) {
        if (feedback == null) {
            return "\"\"";
        }
        String trimmed = feedback.trim();
        String escaped = trimmed.replace("\"", "\"\"");
        return "\"" + escaped + "\"";
    }
    
    /**
     * Loads existing feedback from FinalGrade.txt and displays it in the text area
     */
    private void loadExistingFeedback() {
        String projectRoot = System.getProperty("user.dir");
        String finalGradeFilePath = projectRoot + "\\src\\main\\java\\oopwj\\data\\FinalGrade.txt";
        
        java.io.File finalGradeFile = new java.io.File(finalGradeFilePath);
        if (!finalGradeFile.exists()) {
            logger.log(java.util.logging.Level.WARNING, "FinalGrade.txt not found");
            return;
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(finalGradeFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                    continue;
                }
                
                String[] parts = trimmedLine.split(",", 6);
                if (parts.length >= 6) {
                    String studentIDFromFile = parts[0].trim();
                    String moduleIDFromFile = parts[1].trim();
                    String quizIDFromFile = parts[2].trim();
                    
                    // Match this student's quiz
                    if (studentIDFromFile.equals(studentID) &&
                        moduleIDFromFile.equals(moduleID) &&
                        quizIDFromFile.equals(quizID)) {
                        
                        // Extract feedback (6th column)
                        String feedbackField = parts[5].trim();
                        // Remove surrounding quotes and unescape
                        String feedback = feedbackField;
                        if (feedback.startsWith("\"") && feedback.endsWith("\"")) {
                            feedback = feedback.substring(1, feedback.length() - 1);
                            feedback = feedback.replace("\"\"", "\"");
                        }
                        
                        jTextArea1.setText(feedback);
                        System.out.println("Loaded feedback for student: " + studentID);
                        return;
                    }
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading FinalGrade.txt: " + e.getMessage());
            logger.log(java.util.logging.Level.WARNING, "Error loading feedback: " + e.getMessage());
        }
    }
    
    /**
     * Loads existing quiz set feedback from QuizFeedback.txt
     */
    private void loadExistingQuizSetFeedback() {
        String projectRoot = System.getProperty("user.dir");
        String quizFeedbackFilePath = projectRoot + "\\src\\main\\java\\oopwj\\data\\QuizFeedback.txt";
        
        java.io.File quizFeedbackFile = new java.io.File(quizFeedbackFilePath);
        if (!quizFeedbackFile.exists()) {
            logger.log(java.util.logging.Level.WARNING, "QuizFeedback.txt not found");
            return;
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(quizFeedbackFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                String trimmedLine = line.trim();
                if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                    continue;
                }
                
                String[] parts = trimmedLine.split(",", 4); // Split into max 4 parts
                if (parts.length >= 4) {
                    String moduleIDFromFile = parts[0].trim();
                    String quizIDFromFile = parts[1].trim();
                    String lecturerIDFromFile = parts[2].trim();
                    
                    // Match this quiz and lecturer
                    if (moduleIDFromFile.equals(moduleID) && quizIDFromFile.equals(quizID)
                        && lecturerIDFromFile.equals(lecturerID)) {
                        // Extract feedback (4th column)
                        String feedbackField = parts[3].trim();
                        // Remove surrounding quotes and unescape
                        String feedback = feedbackField;
                        if (feedback.startsWith("\"") && feedback.endsWith("\"")) {
                            feedback = feedback.substring(1, feedback.length() - 1);
                            feedback = feedback.replace("\"\"", "\"");
                        }
                        
                        jTextArea1.setText(feedback);
                        System.out.println("Loaded quiz set feedback for quiz: " + quizID);
                        return;
                    }
                } else if (parts.length == 3) {
                    String moduleIDFromFile = parts[0].trim();
                    String quizIDFromFile = parts[1].trim();

                    if (moduleIDFromFile.equals(moduleID) && quizIDFromFile.equals(quizID)) {
                        String feedbackField = parts[2].trim();
                        String feedback = feedbackField;
                        if (feedback.startsWith("\"") && feedback.endsWith("\"")) {
                            feedback = feedback.substring(1, feedback.length() - 1);
                            feedback = feedback.replace("\"\"", "\"");
                        }
                        jTextArea1.setText(feedback);
                        System.out.println("Loaded quiz set feedback for quiz: " + quizID);
                        return;
                    }
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading QuizFeedback.txt: " + e.getMessage());
            logger.log(java.util.logging.Level.WARNING, "Error loading quiz feedback: " + e.getMessage());
        }
    }
    
    /**
     * Saves quiz set feedback to QuizFeedback.txt
     */
    private boolean saveQuizSetFeedback(String feedback) {
        String projectRoot = System.getProperty("user.dir");
        String quizFeedbackFilePath = projectRoot + "\\src\\main\\java\\oopwj\\data\\QuizFeedback.txt";
        
        java.io.File quizFeedbackFile = new java.io.File(quizFeedbackFilePath);
        java.util.List<String> lines = new java.util.ArrayList<>();
        boolean found = false;
        
        // Read existing content
        if (quizFeedbackFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(quizFeedbackFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String trimmedLine = line.trim();
                    if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                        lines.add(line);
                        continue;
                    }
                    
                    String[] parts = trimmedLine.split(",", 4);
                    if (parts.length >= 4) {
                        String moduleIDFromFile = parts[0].trim();
                        String quizIDFromFile = parts[1].trim();
                        String lecturerIDFromFile = parts[2].trim();
                        
                        // Match this quiz and lecturer
                        if (moduleIDFromFile.equals(moduleID) && quizIDFromFile.equals(quizID)
                            && lecturerIDFromFile.equals(lecturerID)) {
                            // Update with new feedback
                            String formattedFeedback = formatFeedbackField(feedback);
                            String updatedLine = moduleID + "," + quizID + "," + lecturerID + "," + formattedFeedback;
                            lines.add(updatedLine);
                            found = true;
                        } else {
                            lines.add(trimmedLine);
                        }
                    } else if (parts.length >= 2) {
                        String moduleIDFromFile = parts[0].trim();
                        String quizIDFromFile = parts[1].trim();

                        if (moduleIDFromFile.equals(moduleID) && quizIDFromFile.equals(quizID)) {
                            String formattedFeedback = formatFeedbackField(feedback);
                            String updatedLine = moduleID + "," + quizID + "," + lecturerID + "," + formattedFeedback;
                            lines.add(updatedLine);
                            found = true;
                        } else {
                            lines.add(trimmedLine);
                        }
                    } else {
                        lines.add(trimmedLine);
                    }
                }
            } catch (IOException e) {
                System.err.println("Error reading QuizFeedback.txt: " + e.getMessage());
                return false;
            }
        }
        
        // If not found, add new entry
        if (!found) {
            String formattedFeedback = formatFeedbackField(feedback);
            String newLine = moduleID + "," + quizID + "," + lecturerID + "," + formattedFeedback;
            lines.add(newLine);
        }

        sortQuizFeedbackLines(lines);
        
        // Write back to file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(quizFeedbackFile))) {
            for (String line : lines) {
                bw.write(line);
                bw.newLine();
            }
            System.out.println("Saved quiz set feedback to QuizFeedback.txt");
        } catch (IOException e) {
            System.err.println("Error writing to QuizFeedback.txt: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error saving feedback: " + e.getMessage(),
                "File Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

    private void sortQuizFeedbackLines(java.util.List<String> lines) {
        java.util.List<String> dataLines = new java.util.ArrayList<>();
        java.util.List<String> otherLines = new java.util.ArrayList<>();

        for (String line : lines) {
            String trimmedLine = line == null ? "" : line.trim();
            if (trimmedLine.isEmpty() || trimmedLine.startsWith("#")) {
                otherLines.add(line);
                continue;
            }
            dataLines.add(trimmedLine);
        }

        dataLines.sort((a, b) -> {
            String[] partsA = a.split(",", 4);
            String[] partsB = b.split(",", 4);

            String moduleA = partsA.length > 0 ? partsA[0].trim() : "";
            String moduleB = partsB.length > 0 ? partsB[0].trim() : "";
            int moduleCompare = moduleA.compareToIgnoreCase(moduleB);
            if (moduleCompare != 0) {
                return moduleCompare;
            }

            String quizA = partsA.length > 1 ? partsA[1].trim() : "";
            String quizB = partsB.length > 1 ? partsB[1].trim() : "";
            return quizA.compareToIgnoreCase(quizB);
        });

        lines.clear();
        lines.addAll(otherLines);
        lines.addAll(dataLines);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Feedback().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
