/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Grade_Assessment extends javax.swing.JFrame {

    private String lecturerID;
    private Lecturer_menu lecturerMenu;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Grade_Assessment.class.getName());

    /**
     * Creates new form Grade_Assessment
     */
    public Grade_Assessment() {
        initComponents();
        setLocationRelativeTo(null);
        clearTable();
        // No need for initLoadOnShow() here
    }

    public Grade_Assessment(String lecturerID) {
        this(lecturerID, null);
    }
    
    public Grade_Assessment(String lecturerID, Lecturer_menu lecturerMenu) {
        this.lecturerID = lecturerID;
        this.lecturerMenu = lecturerMenu;
        
        System.out.println("Grade_Assessment constructor - lecturerID: " + lecturerID);
        logger.log(java.util.logging.Level.INFO, "Grade_Assessment created with lecturerID: " + lecturerID);
        
        initComponents();
        setLocationRelativeTo(null);
        clearTable();
        initLoadOnShow();
        // REMOVED: loadAssessmentAnswers() - will be called after window is shown
    }

    public void setLecturerID(String lecturerID) {
        this.lecturerID = lecturerID;
        if (isVisible()) {
            reloadAssessmentAnswers();
        }
    }

    private void reloadAssessmentAnswers() {
        clearTable();
        if (lecturerID != null && !lecturerID.isEmpty()) {
            loadAssessmentAnswers();
        }
    }

    private void clearTable() {
        jTable1.setModel(new DefaultTableModel(
            new Object[]{"ModuleID", "StudentID"}, 0
        ));
    }

    private void initLoadOnShow() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                System.out.println("DEBUG: windowOpened called");
                System.out.println("DEBUG: lecturerID = " + lecturerID);
                System.out.println("DEBUG: isVisible = " + isVisible());
                
                if (lecturerID != null && !lecturerID.isEmpty()) {
                    System.out.println("DEBUG: About to load data in background thread");
                    // Load data in background to avoid blocking UI
                    new Thread(() -> {
                        try {
                            Thread.sleep(500); // Wait for window to fully render
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            System.out.println("DEBUG: Calling loadAssessmentAnswers");
                            loadAssessmentAnswers();
                        });
                    }).start();
                } else {
                    System.out.println("DEBUG: lecturerID is null or empty, skipping load");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Grade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Navigate back to lecturer menu
        if (lecturerMenu != null) {
            lecturerMenu.setVisible(true);
        } else {
            Lecturer_menu menu = new Lecturer_menu(lecturerID);
            menu.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void loadAssessmentAnswers() {
        System.out.println("DEBUG: loadAssessmentAnswers() START");
        
        // Use absolute paths based on project root
        String projectRoot = System.getProperty("user.dir");
        String modulesFilePath = projectRoot + "/src/main/java/oopwj/modules.txt";
        String answersFilePath = projectRoot + "/src/main/java/oopwj/answers.txt";
        Set<String> allowedModuleIDs = new HashSet<>();

        // Debug: Check if lecturerID is set
        if (lecturerID == null || lecturerID.isEmpty()) {
            logger.log(java.util.logging.Level.WARNING, "lecturerID is null or empty");
            javax.swing.JOptionPane.showMessageDialog(this, 
                "lecturerID is null or empty", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate file existence
        java.io.File modulesFile = new java.io.File(modulesFilePath);
        java.io.File answersFile = new java.io.File(answersFilePath);
        
        if (!modulesFile.exists()) {
            logger.log(java.util.logging.Level.SEVERE, "modules.txt not found at: " + modulesFile.getAbsolutePath());
            javax.swing.JOptionPane.showMessageDialog(this, 
                "modules.txt not found at: " + modulesFile.getAbsolutePath(), 
                "File Not Found", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!answersFile.exists()) {
            logger.log(java.util.logging.Level.SEVERE, "answers.txt not found at: " + answersFile.getAbsolutePath());
            javax.swing.JOptionPane.showMessageDialog(this, 
                "answers.txt not found at: " + answersFile.getAbsolutePath(), 
                "File Not Found", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        logger.log(java.util.logging.Level.INFO, "Starting load for lecturer: " + lecturerID);
        System.out.println("Project root: " + projectRoot);
        System.out.println("Modules file path: " + modulesFilePath);
        System.out.println("Answers file path: " + answersFilePath);
        System.out.println("LecturerID: '" + lecturerID + "'");
        
        // Build set of moduleIDs for this lecturer
        try (BufferedReader br = new BufferedReader(new FileReader(modulesFile))) {
            String line;
            int lineCount = 0;
            while ((line = br.readLine()) != null) {
                lineCount++;
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                
                String[] parts = line.split(",");
                if (parts.length > 3) {
                    String moduleID = parts[0].trim();
                    String fileLecturerID = parts[3].trim();
                    
                    System.out.println("Comparing: '" + fileLecturerID + "' == '" + lecturerID + "'");
                    if (fileLecturerID.equals(lecturerID)) {
                        allowedModuleIDs.add(moduleID);
                        System.out.println("✓ Found matching module: " + moduleID);
                        logger.log(java.util.logging.Level.INFO, "Found module: " + moduleID);
                    }
                } else {
                    logger.log(java.util.logging.Level.WARNING, "Malformed line in modules.txt (line " + lineCount + "): " + line);
                }
            }
            System.out.println("Total modules read: " + lineCount + ", Allowed: " + allowedModuleIDs.size());
            logger.log(java.util.logging.Level.INFO, "Allowed modules: " + allowedModuleIDs);
        } catch (IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error reading modules.txt: " + e.getMessage(), e);
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error reading modules.txt: " + e.getMessage(), 
                "File Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (allowedModuleIDs.isEmpty()) {
            logger.log(java.util.logging.Level.WARNING, "No modules found for lecturer: " + lecturerID);
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No modules assigned to lecturer: " + lecturerID, 
                "No Data", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Show unique moduleID and studentID pairs only
        Set<String> uniqueStudentModulePairs = new HashSet<>();
        List<String[]> tableData = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(answersFile))) {
            String line;
            int lineCount = 0;
            while ((line = br.readLine()) != null) {
                lineCount++;
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                
                String[] parts = line.split(",");
                if (parts.length >= 5) {
                    String studentID = parts[0].trim();
                    String moduleID = parts[1].trim();
                    
                    if (allowedModuleIDs.contains(moduleID)) {
                        String pairKey = moduleID + "|" + studentID;
                        if (!uniqueStudentModulePairs.contains(pairKey)) {
                            uniqueStudentModulePairs.add(pairKey);
                            tableData.add(new String[]{moduleID, studentID});
                            System.out.println("✓ Added unique student - Module: " + moduleID + ", Student: " + studentID);
                        }
                    }
                } else {
                    logger.log(java.util.logging.Level.WARNING, "Malformed line in answers.txt (line " + lineCount + "): " + line);
                }
            }
            System.out.println("Total answers read: " + lineCount + ", Unique students: " + tableData.size());
            logger.log(java.util.logging.Level.INFO, "Total unique students loaded: " + tableData.size());
        } catch (IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error reading answers.txt: " + e.getMessage(), e);
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error reading answers.txt: " + e.getMessage(), 
                "File Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ModuleID", "StudentID"}, 0
        );
        for (String[] row : tableData) {
            model.addRow(row);
            System.out.println("DEBUG: Added row - " + java.util.Arrays.toString(row));
        }
        System.out.println("DEBUG: Setting model with " + model.getRowCount() + " rows");
        jTable1.setModel(model);
        
        System.out.println("DEBUG: loadAssessmentAnswers() END");
    }   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> 
            new Grade_Assessment("L101").setVisible(true) // Use a valid lecturerID for testing
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
