/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author User
 */
public class Lecturer_menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lecturer_menu.class.getName());
    private String lecturerID;

    /**
     * Creates new form Lecturer_menu
     */
    public Lecturer_menu() {
        this(null);
    }
    
    public Lecturer_menu(String lecturerID) {
        this.lecturerID = lecturerID;
        initComponents();
        centerWindow();
        setupListeners();
        loadWelcomeName();
    }

    private void centerWindow() {
        setLocationRelativeTo(null);
    }
    
    private void setupListeners() {
        Assessmentsbutton.addActionListener(this::AssessmentsbuttonActionPerformed);
    }

    private void loadWelcomeName() {
        if (lecturerID == null || lecturerID.trim().isEmpty()) {
            welcome.setText("Welcome");
            return;
        }

        String lecturerName = null;
        try (BufferedReader br = new BufferedReader(new FileReader("src/main/java/oopwj/Data/lecturer.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 2 && parts[0].equals(lecturerID)) {
                    lecturerName = parts[1];
                    break;
                }
            }
        } catch (IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading lecturer data", e);
        }

        if (lecturerName == null || lecturerName.trim().isEmpty()) {
            welcome.setText("Welcome");
        } else {
            welcome.setText("Welcome, " + lecturerName.trim());
        }
    }
    
    public void clearSession() {
        this.lecturerID = null;
        logger.info("Academic Leader session cleared");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editProfile = new javax.swing.JButton();
        Assessmentsbutton = new javax.swing.JButton();
        GradeAssessmentButton = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        editProfile.setText("Edit Profile");
        editProfile.setAlignmentX(0.5F);
        editProfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editProfile.addActionListener(this::editProfileActionPerformed);

        Assessmentsbutton.setText("Assessments");
        Assessmentsbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        GradeAssessmentButton.setText("Grade Assessment");
        GradeAssessmentButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GradeAssessmentButton.addActionListener(this::GradeAssessmentButtonActionPerformed);

        logOut.setText("Log Out");
        logOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logOut.addActionListener(this::logOutActionPerformed);

        jButton1.setText("Timetable");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(this::jButton1ActionPerformed);

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcome.setText("Welcome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(editProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Assessmentsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GradeAssessmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(welcome)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(welcome)
                .addGap(50, 50, 50)
                .addComponent(editProfile)
                .addGap(18, 18, 18)
                .addComponent(Assessmentsbutton)
                .addGap(18, 18, 18)
                .addComponent(GradeAssessmentButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(logOut)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Lecturer_schedule(lecturerID, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed
        // TODO add your handling code here:
        new editProfileL(lecturerID,this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editProfileActionPerformed

    private void GradeAssessmentButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new Grade_Assessment(lecturerID, this).setVisible(true);
        this.setVisible(false);
    }                                                     

    private void CreateAssessmentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Assessments().setVisible(true);
        this.dispose();
    }

    private void AssessmentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Assessments(lecturerID, this).setVisible(true);
        this.setVisible(false);
    }

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            clearSession();  // Clear user session
            this.dispose();
            new oopwj.LoginFrame();  // Return to login page
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lecturer_menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assessmentsbutton;
    private javax.swing.JButton GradeAssessmentButton;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
