/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

/**
 *
 * @author User
 */
public class Lecturer_menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lecturer_menu.class.getName());

    /**
     * Creates new form Lecturer_menu
     */
    public Lecturer_menu() {
        initComponents();
        setupListeners();
    }

    private void setupListeners() {
        Settings.addActionListener(this::SettingsActionPerformed);
        Assessmentsbutton.addActionListener(this::AssessmentsbuttonActionPerformed);
        AssessmentMarkButton.addActionListener(this::AssessmentMarkButtonActionPerformed);
        AssessmentFeedbackButton.addActionListener(this::AssessmentFeedbackButtonActionPerformed);
        EditAssessmentsbutton.addActionListener(this::EditAssessmentsbuttonActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Settings = new javax.swing.JButton();
        Assessmentsbutton = new javax.swing.JButton();
        AssessmentMarkButton = new javax.swing.JButton();
        AssessmentFeedbackButton = new javax.swing.JButton();
        EditAssessmentsbutton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Settings.setText("Settings");
        Settings.setAlignmentX(0.5F);
        Settings.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Assessmentsbutton.setText("Assessments");
        Assessmentsbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AssessmentMarkButton.setText("Assessment Marks");
        AssessmentMarkButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AssessmentFeedbackButton.setText("Assessment Feedback");
        AssessmentFeedbackButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EditAssessmentsbutton.setText("Edit Assessments");
        EditAssessmentsbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BackButton.addActionListener(this::BackButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Assessmentsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AssessmentMarkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditAssessmentsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AssessmentFeedbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Settings)
                .addGap(18, 18, 18)
                .addComponent(Assessmentsbutton)
                .addGap(18, 18, 18)
                .addComponent(EditAssessmentsbutton)
                .addGap(18, 18, 18)
                .addComponent(AssessmentMarkButton)
                .addGap(18, 18, 18)
                .addComponent(AssessmentFeedbackButton)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {
        new Lecturer_Settings().setVisible(true);
        this.dispose();
    }

    private void CreateAssessmentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Assessments().setVisible(true);
        this.dispose();
    }

    private void AssessmentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Assessments().setVisible(true);
        this.dispose();
    }

    private void EditAssessmentsbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        new Edit_Assessment().setVisible(true);
        this.dispose();
    }

    private void AssessmentMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new Assessment_Marks().setVisible(true);
        this.dispose();
    }

    private void AssessmentFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new Assessment_Feedback().setVisible(true);
        this.dispose();
    }

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lecturer_menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssessmentFeedbackButton;
    private javax.swing.JButton AssessmentMarkButton;
    private javax.swing.JButton Assessmentsbutton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditAssessmentsbutton;
    private javax.swing.JButton Settings;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
