/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopwj.Lecturer;

/**
 *
 * @author User
 */
public class View_Grade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View_Grade.class.getName());
    private String lecturerID;
    private String moduleID;
    private String quizID;
    private String studentID;

    /**
     * Creates new form View_Grade
     */
    public View_Grade() {
        initComponents();
        setLocationRelativeTo(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
    }
    
    /**
     * Creates new form View_Grade with moduleID, quizID, studentID, and lecturerID
     */
    public View_Grade(String moduleID, String quizID, String studentID, String lecturerID) {
        this.lecturerID = lecturerID;
        this.moduleID = moduleID;
        this.quizID = quizID;
        this.studentID = studentID;
        initComponents();
        setLocationRelativeTo(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        setModuleAndStudentInfo(moduleID, studentID);
        loadQuestionIDs(moduleID, quizID);
    }
    
    /**
     * Sets the module ID, quiz ID, and student ID on the labels
     */
    public void setModuleAndStudentInfo(String moduleID, String studentID) {
        jLabel7.setText("Module ID: " + moduleID);
        jLabel8.setText("Student ID: " + studentID);
        jLabel9.setText("Quiz ID: " + quizID);
    }
    
    /**
     * Loads all QuestionIDs for the given moduleID and quizID from question.txt
     */
    private void loadQuestionIDs(String moduleID, String quizID) {
        String projectRoot = System.getProperty("user.dir");
        String quizFilePath = projectRoot + "/src/main/java/oopwj/question.txt";
        
        java.io.File quizFile = new java.io.File(quizFilePath);
        if (!quizFile.exists()) {
            logger.log(java.util.logging.Level.SEVERE, "question.txt not found at: " + quizFile.getAbsolutePath());
            javax.swing.JOptionPane.showMessageDialog(this, 
                "question.txt not found at: " + quizFile.getAbsolutePath(), 
                "File Not Found", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Clear existing items
        jComboBox1.removeAllItems();
        
        java.util.Set<String> questionIDs = new java.util.LinkedHashSet<>();
        
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(quizFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                
                String[] parts = line.split(",");
                if (parts.length >= 3) {
                    String questionID = parts[0].trim();
                    String fileQuizID = parts[1].trim();
                    String fileModuleID = parts[2].trim();
                    
                    if (fileModuleID.equals(moduleID) && fileQuizID.equals(quizID)) {
                        questionIDs.add(questionID);
                    }
                }
            }
            
            // Populate combo box
            for (String qid : questionIDs) {
                jComboBox1.addItem(qid);
            }
            
            logger.log(java.util.logging.Level.INFO, "Loaded " + questionIDs.size() + " questions for module: " + moduleID + ", quiz: " + quizID);
            
        } catch (java.io.IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error reading question.txt: " + e.getMessage(), e);
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error reading question.txt: " + e.getMessage(), 
                "File Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        Objective = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Subjective = new javax.swing.JPanel();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setSize(new java.awt.Dimension(734, 617));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        Objective.setBackground(new java.awt.Color(255, 255, 255));
        Objective.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField1.setEditable(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Answer:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correct Answer:");

        jTextField2.setEditable(false);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Incorrect");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("Correct");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Question:");

        javax.swing.GroupLayout ObjectiveLayout = new javax.swing.GroupLayout(Objective);
        Objective.setLayout(ObjectiveLayout);
        ObjectiveLayout.setHorizontalGroup(
            ObjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObjectiveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(ObjectiveLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ObjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(ObjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ObjectiveLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(ObjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ObjectiveLayout.setVerticalGroup(
            ObjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObjectiveLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(ObjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(28, 28, 28))
        );

        jLayeredPane2.add(Objective, "card3");

        Subjective.setBackground(new java.awt.Color(255, 255, 255));
        Subjective.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Question:");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Answer:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Marks Given:");

        javax.swing.GroupLayout SubjectiveLayout = new javax.swing.GroupLayout(Subjective);
        Subjective.setLayout(SubjectiveLayout);
        SubjectiveLayout.setHorizontalGroup(
            SubjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectiveLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(SubjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SubjectiveLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        SubjectiveLayout.setVerticalGroup(
            SubjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectiveLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(SubjectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41))
        );

        jLayeredPane2.add(Subjective, "card2");

        jPanel4.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 420, 420));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 30));

        jButton1.setText("Exit");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Module ID:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Student ID:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Quiz ID: ");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Get the selected question ID from the combo box
        String selectedQuestionID = (String) jComboBox1.getSelectedItem();
        if (selectedQuestionID == null || selectedQuestionID.isEmpty()) {
            return;
        }
        
        // Load question data from question.txt
        loadQuestionData(selectedQuestionID);
        
        // Load student answer from answers.txt
        loadStudentAnswer(selectedQuestionID);
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    /**
     * Loads question data from question.txt and displays it in the appropriate panel
     */
    private void loadQuestionData(String questionID) {
        String projectRoot = System.getProperty("user.dir");
        String questionFilePath = projectRoot + "/src/main/java/oopwj/question.txt";
        
        java.io.File questionFile = new java.io.File(questionFilePath);
        if (!questionFile.exists()) {
            logger.log(java.util.logging.Level.SEVERE, "question.txt not found");
            return;
        }
        
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(questionFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                
                String[] parts = line.split(",");
                if (parts.length >= 3) {
                    String fileQuestionID = parts[0].trim();
                    String fileQuizID = parts[1].trim();
                    String fileModuleID = parts[2].trim();
                    
                    if (fileQuestionID.equals(questionID) && fileQuizID.equals(quizID) && fileModuleID.equals(moduleID)) {
                        if (parts.length >= 10) {
                            // Objective question format: QuestionID,QuizID,ModuleID,Question,A,B,C,D,CorrectAnswer,Type
                            String question = parts[3].trim().replaceAll("^\\\"|\\\"$", "");
                            String answerA = parts[4].trim().replaceAll("^\\\"|\\\"$", "");
                            String answerB = parts[5].trim().replaceAll("^\\\"|\\\"$", "");
                            String answerC = parts[6].trim().replaceAll("^\\\"|\\\"$", "");
                            String answerD = parts[7].trim().replaceAll("^\\\"|\\\"$", "");
                            String correctAnswer = parts[8].trim().replaceAll("^\\\"|\\\"$", "");
                            
                            // Fill objective panel
                            jTextArea1.setText(question);
                            jTextField1.setText(answerA + " / " + answerB + " / " + answerC + " / " + answerD);
                            jTextField2.setText(correctAnswer);
                            
                            // Show objective panel
                            swapPanels("Objective");
                        } else if (parts.length >= 5) {
                            // Subjective question format: QuestionID,QuizID,ModuleID,Question,Type
                            String question = parts[3].trim().replaceAll("^\\\"|\\\"$", "");
                            
                            // Fill subjective panel
                            jTextArea2.setText(question);
                            
                            // Show subjective panel
                            swapPanels("Subjective");
                        }
                        return;
                    }
                }
            }
        } catch (java.io.IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error reading question.txt: " + e.getMessage(), e);
        }
    }
    
    /**
     * Loads student answer from answers.txt and displays it
     */
    private void loadStudentAnswer(String questionID) {
        String projectRoot = System.getProperty("user.dir");
        String answersFilePath = projectRoot + "/src/main/java/oopwj/answers.txt";
        
        java.io.File answersFile = new java.io.File(answersFilePath);
        if (!answersFile.exists()) {
            logger.log(java.util.logging.Level.SEVERE, "answers.txt not found");
            return;
        }
        
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(answersFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                
                // Format: StudentID,ModuleID,QuizID,QuestionID,QuestionType,Answer
                String[] parts = line.split(",");
                if (parts.length >= 6) {
                    String fileStudentID = parts[0].trim();
                    String fileModuleID = parts[1].trim();
                    String fileQuizID = parts[2].trim();
                    String fileQuestionID = parts[3].trim();
                    String questionType = parts[4].trim();
                    String answer = parts[5].trim();
                    
                    if (fileStudentID.equals(studentID) && fileModuleID.equals(moduleID) && 
                        fileQuizID.equals(quizID) && fileQuestionID.equals(questionID)) {
                        
                        if ("Objective".equalsIgnoreCase(questionType)) {
                            // Set objective answer radio buttons
                            if ("A".equalsIgnoreCase(answer)) {
                                jRadioButton1.setSelected(true);
                            } else if ("B".equalsIgnoreCase(answer)) {
                                jRadioButton2.setSelected(true);
                            }
                            // Add more radio buttons if you have C and D
                        } else if ("Subjective".equalsIgnoreCase(questionType)) {
                            // Set subjective answer
                            jTextArea3.setText(answer);
                        }
                        return;
                    }
                }
            }
        } catch (java.io.IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error reading answers.txt: " + e.getMessage(), e);
        }
    }
    
    /**
     * Swaps the visible panel between Objective and Subjective based on question type
     * @param questionType the type of question (Subjective or Objective)
     */
    private void swapPanels(String questionType) {
        java.awt.CardLayout cl = (java.awt.CardLayout) jLayeredPane2.getLayout();
        
        if ("Subjective".equalsIgnoreCase(questionType)) {
            cl.show(jLayeredPane2, "card2");
            logger.log(java.util.logging.Level.INFO, "Showing Subjective panel");
        } else if ("Objective".equalsIgnoreCase(questionType)) {
            cl.show(jLayeredPane2, "card3");
            logger.log(java.util.logging.Level.INFO, "Showing Objective panel");
        } else {
            logger.log(java.util.logging.Level.WARNING, "Unknown question type: " + questionType);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate back to Grade_Assessment
        Grade_Assessment gradeAssessment = new Grade_Assessment(lecturerID);
        gradeAssessment.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View_Grade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Objective;
    private javax.swing.JPanel Subjective;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
